// <auto-generated>
/*
 * SignWell Developer API
 *
 * API for creating, managing, and tracking electronic signature workflows.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@signwell.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using SignWell.Sdk.Client;

namespace SignWell.Sdk.Models
{
    /// <summary>
    /// AccountInfoResponsePreferences
    /// </summary>
    public partial class AccountInfoResponsePreferences : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AccountInfoResponsePreferences" /> class.
        /// </summary>
        /// <param name="dateFormat">dateFormat</param>
        /// <param name="daysUntilLinksExpire">daysUntilLinksExpire</param>
        /// <param name="disableApplyEverywhere">disableApplyEverywhere</param>
        /// <param name="disableApplyEverywhereEffective">disableApplyEverywhereEffective</param>
        /// <param name="disableDrawnSignatures">disableDrawnSignatures</param>
        /// <param name="disableTypedSignatures">disableTypedSignatures</param>
        /// <param name="disableUploadedSignatures">disableUploadedSignatures</param>
        /// <param name="enableRedirect">enableRedirect</param>
        /// <param name="hideDocumentIdInAudit">hideDocumentIdInAudit</param>
        /// <param name="muteBranding">muteBranding</param>
        /// <param name="redirectUrl">redirectUrl</param>
        /// <param name="separateAuditPdf">separateAuditPdf</param>
        /// <param name="separateCompletedFile">separateCompletedFile</param>
        /// <param name="enableNom151Compliance">enableNom151Compliance</param>
        [JsonConstructor]
        public AccountInfoResponsePreferences(Option<string?> dateFormat = default, Option<int?> daysUntilLinksExpire = default, Option<bool?> disableApplyEverywhere = default, Option<bool?> disableApplyEverywhereEffective = default, Option<bool?> disableDrawnSignatures = default, Option<bool?> disableTypedSignatures = default, Option<bool?> disableUploadedSignatures = default, Option<bool?> enableRedirect = default, Option<bool?> hideDocumentIdInAudit = default, Option<bool?> muteBranding = default, Option<string?> redirectUrl = default, Option<bool?> separateAuditPdf = default, Option<bool?> separateCompletedFile = default, Option<bool?> enableNom151Compliance = default)
        {
            DateFormatOption = dateFormat;
            DaysUntilLinksExpireOption = daysUntilLinksExpire;
            DisableApplyEverywhereOption = disableApplyEverywhere;
            DisableApplyEverywhereEffectiveOption = disableApplyEverywhereEffective;
            DisableDrawnSignaturesOption = disableDrawnSignatures;
            DisableTypedSignaturesOption = disableTypedSignatures;
            DisableUploadedSignaturesOption = disableUploadedSignatures;
            EnableRedirectOption = enableRedirect;
            HideDocumentIdInAuditOption = hideDocumentIdInAudit;
            MuteBrandingOption = muteBranding;
            RedirectUrlOption = redirectUrl;
            SeparateAuditPdfOption = separateAuditPdf;
            SeparateCompletedFileOption = separateCompletedFile;
            EnableNom151ComplianceOption = enableNom151Compliance;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of DateFormat
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> DateFormatOption { get; private set; }

        /// <summary>
        /// Gets or Sets DateFormat
        /// </summary>
        [JsonPropertyName("date_format")]
        public string? DateFormat { get { return this.DateFormatOption.Value; } set { this.DateFormatOption = new Option<string?>(value); } }

        /// <summary>
        /// Used to track the state of DaysUntilLinksExpire
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> DaysUntilLinksExpireOption { get; private set; }

        /// <summary>
        /// Gets or Sets DaysUntilLinksExpire
        /// </summary>
        [JsonPropertyName("days_until_links_expire")]
        public int? DaysUntilLinksExpire { get { return this.DaysUntilLinksExpireOption.Value; } set { this.DaysUntilLinksExpireOption = new Option<int?>(value); } }

        /// <summary>
        /// Used to track the state of DisableApplyEverywhere
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> DisableApplyEverywhereOption { get; private set; }

        /// <summary>
        /// Gets or Sets DisableApplyEverywhere
        /// </summary>
        [JsonPropertyName("disable_apply_everywhere")]
        public bool? DisableApplyEverywhere { get { return this.DisableApplyEverywhereOption.Value; } set { this.DisableApplyEverywhereOption = new Option<bool?>(value); } }

        /// <summary>
        /// Used to track the state of DisableApplyEverywhereEffective
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> DisableApplyEverywhereEffectiveOption { get; private set; }

        /// <summary>
        /// Gets or Sets DisableApplyEverywhereEffective
        /// </summary>
        [JsonPropertyName("disable_apply_everywhere_effective")]
        public bool? DisableApplyEverywhereEffective { get { return this.DisableApplyEverywhereEffectiveOption.Value; } set { this.DisableApplyEverywhereEffectiveOption = new Option<bool?>(value); } }

        /// <summary>
        /// Used to track the state of DisableDrawnSignatures
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> DisableDrawnSignaturesOption { get; private set; }

        /// <summary>
        /// Gets or Sets DisableDrawnSignatures
        /// </summary>
        [JsonPropertyName("disable_drawn_signatures")]
        public bool? DisableDrawnSignatures { get { return this.DisableDrawnSignaturesOption.Value; } set { this.DisableDrawnSignaturesOption = new Option<bool?>(value); } }

        /// <summary>
        /// Used to track the state of DisableTypedSignatures
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> DisableTypedSignaturesOption { get; private set; }

        /// <summary>
        /// Gets or Sets DisableTypedSignatures
        /// </summary>
        [JsonPropertyName("disable_typed_signatures")]
        public bool? DisableTypedSignatures { get { return this.DisableTypedSignaturesOption.Value; } set { this.DisableTypedSignaturesOption = new Option<bool?>(value); } }

        /// <summary>
        /// Used to track the state of DisableUploadedSignatures
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> DisableUploadedSignaturesOption { get; private set; }

        /// <summary>
        /// Gets or Sets DisableUploadedSignatures
        /// </summary>
        [JsonPropertyName("disable_uploaded_signatures")]
        public bool? DisableUploadedSignatures { get { return this.DisableUploadedSignaturesOption.Value; } set { this.DisableUploadedSignaturesOption = new Option<bool?>(value); } }

        /// <summary>
        /// Used to track the state of EnableRedirect
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> EnableRedirectOption { get; private set; }

        /// <summary>
        /// Gets or Sets EnableRedirect
        /// </summary>
        [JsonPropertyName("enable_redirect")]
        public bool? EnableRedirect { get { return this.EnableRedirectOption.Value; } set { this.EnableRedirectOption = new Option<bool?>(value); } }

        /// <summary>
        /// Used to track the state of HideDocumentIdInAudit
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> HideDocumentIdInAuditOption { get; private set; }

        /// <summary>
        /// Gets or Sets HideDocumentIdInAudit
        /// </summary>
        [JsonPropertyName("hide_document_id_in_audit")]
        public bool? HideDocumentIdInAudit { get { return this.HideDocumentIdInAuditOption.Value; } set { this.HideDocumentIdInAuditOption = new Option<bool?>(value); } }

        /// <summary>
        /// Used to track the state of MuteBranding
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> MuteBrandingOption { get; private set; }

        /// <summary>
        /// Gets or Sets MuteBranding
        /// </summary>
        [JsonPropertyName("mute_branding")]
        public bool? MuteBranding { get { return this.MuteBrandingOption.Value; } set { this.MuteBrandingOption = new Option<bool?>(value); } }

        /// <summary>
        /// Used to track the state of RedirectUrl
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> RedirectUrlOption { get; private set; }

        /// <summary>
        /// Gets or Sets RedirectUrl
        /// </summary>
        [JsonPropertyName("redirect_url")]
        public string? RedirectUrl { get { return this.RedirectUrlOption.Value; } set { this.RedirectUrlOption = new Option<string?>(value); } }

        /// <summary>
        /// Used to track the state of SeparateAuditPdf
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> SeparateAuditPdfOption { get; private set; }

        /// <summary>
        /// Gets or Sets SeparateAuditPdf
        /// </summary>
        [JsonPropertyName("separate_audit_pdf")]
        public bool? SeparateAuditPdf { get { return this.SeparateAuditPdfOption.Value; } set { this.SeparateAuditPdfOption = new Option<bool?>(value); } }

        /// <summary>
        /// Used to track the state of SeparateCompletedFile
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> SeparateCompletedFileOption { get; private set; }

        /// <summary>
        /// Gets or Sets SeparateCompletedFile
        /// </summary>
        [JsonPropertyName("separate_completed_file")]
        public bool? SeparateCompletedFile { get { return this.SeparateCompletedFileOption.Value; } set { this.SeparateCompletedFileOption = new Option<bool?>(value); } }

        /// <summary>
        /// Used to track the state of EnableNom151Compliance
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> EnableNom151ComplianceOption { get; private set; }

        /// <summary>
        /// Gets or Sets EnableNom151Compliance
        /// </summary>
        [JsonPropertyName("enable_nom151_compliance")]
        public bool? EnableNom151Compliance { get { return this.EnableNom151ComplianceOption.Value; } set { this.EnableNom151ComplianceOption = new Option<bool?>(value); } }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AccountInfoResponsePreferences {\n");
            sb.Append("  DateFormat: ").Append(DateFormat).Append("\n");
            sb.Append("  DaysUntilLinksExpire: ").Append(DaysUntilLinksExpire).Append("\n");
            sb.Append("  DisableApplyEverywhere: ").Append(DisableApplyEverywhere).Append("\n");
            sb.Append("  DisableApplyEverywhereEffective: ").Append(DisableApplyEverywhereEffective).Append("\n");
            sb.Append("  DisableDrawnSignatures: ").Append(DisableDrawnSignatures).Append("\n");
            sb.Append("  DisableTypedSignatures: ").Append(DisableTypedSignatures).Append("\n");
            sb.Append("  DisableUploadedSignatures: ").Append(DisableUploadedSignatures).Append("\n");
            sb.Append("  EnableRedirect: ").Append(EnableRedirect).Append("\n");
            sb.Append("  HideDocumentIdInAudit: ").Append(HideDocumentIdInAudit).Append("\n");
            sb.Append("  MuteBranding: ").Append(MuteBranding).Append("\n");
            sb.Append("  RedirectUrl: ").Append(RedirectUrl).Append("\n");
            sb.Append("  SeparateAuditPdf: ").Append(SeparateAuditPdf).Append("\n");
            sb.Append("  SeparateCompletedFile: ").Append(SeparateCompletedFile).Append("\n");
            sb.Append("  EnableNom151Compliance: ").Append(EnableNom151Compliance).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="AccountInfoResponsePreferences" />
    /// </summary>
    public class AccountInfoResponsePreferencesJsonConverter : JsonConverter<AccountInfoResponsePreferences>
    {
        /// <summary>
        /// Deserializes json to <see cref="AccountInfoResponsePreferences" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override AccountInfoResponsePreferences Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> dateFormat = default;
            Option<int?> daysUntilLinksExpire = default;
            Option<bool?> disableApplyEverywhere = default;
            Option<bool?> disableApplyEverywhereEffective = default;
            Option<bool?> disableDrawnSignatures = default;
            Option<bool?> disableTypedSignatures = default;
            Option<bool?> disableUploadedSignatures = default;
            Option<bool?> enableRedirect = default;
            Option<bool?> hideDocumentIdInAudit = default;
            Option<bool?> muteBranding = default;
            Option<string?> redirectUrl = default;
            Option<bool?> separateAuditPdf = default;
            Option<bool?> separateCompletedFile = default;
            Option<bool?> enableNom151Compliance = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "date_format":
                            dateFormat = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "days_until_links_expire":
                            daysUntilLinksExpire = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "disable_apply_everywhere":
                            disableApplyEverywhere = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "disable_apply_everywhere_effective":
                            disableApplyEverywhereEffective = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "disable_drawn_signatures":
                            disableDrawnSignatures = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "disable_typed_signatures":
                            disableTypedSignatures = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "disable_uploaded_signatures":
                            disableUploadedSignatures = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "enable_redirect":
                            enableRedirect = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "hide_document_id_in_audit":
                            hideDocumentIdInAudit = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "mute_branding":
                            muteBranding = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "redirect_url":
                            redirectUrl = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "separate_audit_pdf":
                            separateAuditPdf = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "separate_completed_file":
                            separateCompletedFile = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "enable_nom151_compliance":
                            enableNom151Compliance = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (dateFormat.IsSet && dateFormat.Value == null)
                throw new ArgumentNullException(nameof(dateFormat), "Property is not nullable for class AccountInfoResponsePreferences.");

            if (daysUntilLinksExpire.IsSet && daysUntilLinksExpire.Value == null)
                throw new ArgumentNullException(nameof(daysUntilLinksExpire), "Property is not nullable for class AccountInfoResponsePreferences.");

            if (disableApplyEverywhere.IsSet && disableApplyEverywhere.Value == null)
                throw new ArgumentNullException(nameof(disableApplyEverywhere), "Property is not nullable for class AccountInfoResponsePreferences.");

            if (disableApplyEverywhereEffective.IsSet && disableApplyEverywhereEffective.Value == null)
                throw new ArgumentNullException(nameof(disableApplyEverywhereEffective), "Property is not nullable for class AccountInfoResponsePreferences.");

            if (disableDrawnSignatures.IsSet && disableDrawnSignatures.Value == null)
                throw new ArgumentNullException(nameof(disableDrawnSignatures), "Property is not nullable for class AccountInfoResponsePreferences.");

            if (disableTypedSignatures.IsSet && disableTypedSignatures.Value == null)
                throw new ArgumentNullException(nameof(disableTypedSignatures), "Property is not nullable for class AccountInfoResponsePreferences.");

            if (disableUploadedSignatures.IsSet && disableUploadedSignatures.Value == null)
                throw new ArgumentNullException(nameof(disableUploadedSignatures), "Property is not nullable for class AccountInfoResponsePreferences.");

            if (enableRedirect.IsSet && enableRedirect.Value == null)
                throw new ArgumentNullException(nameof(enableRedirect), "Property is not nullable for class AccountInfoResponsePreferences.");

            if (hideDocumentIdInAudit.IsSet && hideDocumentIdInAudit.Value == null)
                throw new ArgumentNullException(nameof(hideDocumentIdInAudit), "Property is not nullable for class AccountInfoResponsePreferences.");

            if (muteBranding.IsSet && muteBranding.Value == null)
                throw new ArgumentNullException(nameof(muteBranding), "Property is not nullable for class AccountInfoResponsePreferences.");

            if (separateAuditPdf.IsSet && separateAuditPdf.Value == null)
                throw new ArgumentNullException(nameof(separateAuditPdf), "Property is not nullable for class AccountInfoResponsePreferences.");

            if (separateCompletedFile.IsSet && separateCompletedFile.Value == null)
                throw new ArgumentNullException(nameof(separateCompletedFile), "Property is not nullable for class AccountInfoResponsePreferences.");

            if (enableNom151Compliance.IsSet && enableNom151Compliance.Value == null)
                throw new ArgumentNullException(nameof(enableNom151Compliance), "Property is not nullable for class AccountInfoResponsePreferences.");

            return new AccountInfoResponsePreferences(dateFormat, daysUntilLinksExpire, disableApplyEverywhere, disableApplyEverywhereEffective, disableDrawnSignatures, disableTypedSignatures, disableUploadedSignatures, enableRedirect, hideDocumentIdInAudit, muteBranding, redirectUrl, separateAuditPdf, separateCompletedFile, enableNom151Compliance);
        }

        /// <summary>
        /// Serializes a <see cref="AccountInfoResponsePreferences" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="accountInfoResponsePreferences"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, AccountInfoResponsePreferences accountInfoResponsePreferences, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, accountInfoResponsePreferences, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="AccountInfoResponsePreferences" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="accountInfoResponsePreferences"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, AccountInfoResponsePreferences accountInfoResponsePreferences, JsonSerializerOptions jsonSerializerOptions)
        {
            if (accountInfoResponsePreferences.DateFormatOption.IsSet && accountInfoResponsePreferences.DateFormat == null)
                throw new ArgumentNullException(nameof(accountInfoResponsePreferences.DateFormat), "Property is required for class AccountInfoResponsePreferences.");

            if (accountInfoResponsePreferences.DateFormatOption.IsSet)
                writer.WriteString("date_format", accountInfoResponsePreferences.DateFormat);

            if (accountInfoResponsePreferences.DaysUntilLinksExpireOption.IsSet)
                writer.WriteNumber("days_until_links_expire", accountInfoResponsePreferences.DaysUntilLinksExpireOption.Value!.Value);

            if (accountInfoResponsePreferences.DisableApplyEverywhereOption.IsSet)
                writer.WriteBoolean("disable_apply_everywhere", accountInfoResponsePreferences.DisableApplyEverywhereOption.Value!.Value);

            if (accountInfoResponsePreferences.DisableApplyEverywhereEffectiveOption.IsSet)
                writer.WriteBoolean("disable_apply_everywhere_effective", accountInfoResponsePreferences.DisableApplyEverywhereEffectiveOption.Value!.Value);

            if (accountInfoResponsePreferences.DisableDrawnSignaturesOption.IsSet)
                writer.WriteBoolean("disable_drawn_signatures", accountInfoResponsePreferences.DisableDrawnSignaturesOption.Value!.Value);

            if (accountInfoResponsePreferences.DisableTypedSignaturesOption.IsSet)
                writer.WriteBoolean("disable_typed_signatures", accountInfoResponsePreferences.DisableTypedSignaturesOption.Value!.Value);

            if (accountInfoResponsePreferences.DisableUploadedSignaturesOption.IsSet)
                writer.WriteBoolean("disable_uploaded_signatures", accountInfoResponsePreferences.DisableUploadedSignaturesOption.Value!.Value);

            if (accountInfoResponsePreferences.EnableRedirectOption.IsSet)
                writer.WriteBoolean("enable_redirect", accountInfoResponsePreferences.EnableRedirectOption.Value!.Value);

            if (accountInfoResponsePreferences.HideDocumentIdInAuditOption.IsSet)
                writer.WriteBoolean("hide_document_id_in_audit", accountInfoResponsePreferences.HideDocumentIdInAuditOption.Value!.Value);

            if (accountInfoResponsePreferences.MuteBrandingOption.IsSet)
                writer.WriteBoolean("mute_branding", accountInfoResponsePreferences.MuteBrandingOption.Value!.Value);

            if (accountInfoResponsePreferences.RedirectUrlOption.IsSet)
                if (accountInfoResponsePreferences.RedirectUrlOption.Value != null)
                    writer.WriteString("redirect_url", accountInfoResponsePreferences.RedirectUrl);
                else
                    writer.WriteNull("redirect_url");

            if (accountInfoResponsePreferences.SeparateAuditPdfOption.IsSet)
                writer.WriteBoolean("separate_audit_pdf", accountInfoResponsePreferences.SeparateAuditPdfOption.Value!.Value);

            if (accountInfoResponsePreferences.SeparateCompletedFileOption.IsSet)
                writer.WriteBoolean("separate_completed_file", accountInfoResponsePreferences.SeparateCompletedFileOption.Value!.Value);

            if (accountInfoResponsePreferences.EnableNom151ComplianceOption.IsSet)
                writer.WriteBoolean("enable_nom151_compliance", accountInfoResponsePreferences.EnableNom151ComplianceOption.Value!.Value);
        }
    }
}
