// <auto-generated>
/*
 * SignWell Developer API
 *
 * API for creating, managing, and tracking electronic signature workflows.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@signwell.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using SignWell.Sdk.Client;

namespace SignWell.Sdk.Models
{
    /// <summary>
    /// Additional files to be appended to the document. Will not replace existing files from the template. Document files can be uploaded by specifying a file URL or base64 string. Either &#x60;file_url&#x60; or &#x60;file_base64&#x60; must be present (not both). Valid file types are: .pdf, .docx, .jpg, .png, .ppt, .xls, .pages, and .txt.
    /// </summary>
    public partial class AdditionalFilesInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AdditionalFilesInner" /> class.
        /// </summary>
        /// <param name="name">Name of the file that will be uploaded.</param>
        /// <param name="fileUrl">Publicly available URL of the file to be uploaded.</param>
        /// <param name="fileBase64">A RFC 4648 base64 string of the file to be uploaded.</param>
        [JsonConstructor]
        public AdditionalFilesInner(string name, Option<string?> fileUrl = default, Option<byte[]?> fileBase64 = default)
        {
            Name = name;
            FileUrlOption = fileUrl;
            FileBase64Option = fileBase64;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Name of the file that will be uploaded.
        /// </summary>
        /// <value>Name of the file that will be uploaded.</value>
        [JsonPropertyName("name")]
        public string Name { get; set; }

        /// <summary>
        /// Used to track the state of FileUrl
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> FileUrlOption { get; private set; }

        /// <summary>
        /// Publicly available URL of the file to be uploaded.
        /// </summary>
        /// <value>Publicly available URL of the file to be uploaded.</value>
        [JsonPropertyName("file_url")]
        public string? FileUrl { get { return this.FileUrlOption.Value; } set { this.FileUrlOption = new Option<string?>(value); } }

        /// <summary>
        /// Used to track the state of FileBase64
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<byte[]?> FileBase64Option { get; private set; }

        /// <summary>
        /// A RFC 4648 base64 string of the file to be uploaded.
        /// </summary>
        /// <value>A RFC 4648 base64 string of the file to be uploaded.</value>
        [JsonPropertyName("file_base64")]
        public byte[]? FileBase64 { get { return this.FileBase64Option.Value; } set { this.FileBase64Option = new Option<byte[]?>(value); } }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AdditionalFilesInner {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  FileUrl: ").Append(FileUrl).Append("\n");
            sb.Append("  FileBase64: ").Append(FileBase64).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="AdditionalFilesInner" />
    /// </summary>
    public class AdditionalFilesInnerJsonConverter : JsonConverter<AdditionalFilesInner>
    {
        /// <summary>
        /// Deserializes json to <see cref="AdditionalFilesInner" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override AdditionalFilesInner Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> name = default;
            Option<string?> fileUrl = default;
            Option<byte[]?> fileBase64 = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "file_url":
                            fileUrl = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "file_base64":
                            fileBase64 = new Option<byte[]?>(JsonSerializer.Deserialize<byte[]>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!name.IsSet)
                throw new ArgumentException("Property is required for class AdditionalFilesInner.", nameof(name));

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class AdditionalFilesInner.");

            if (fileUrl.IsSet && fileUrl.Value == null)
                throw new ArgumentNullException(nameof(fileUrl), "Property is not nullable for class AdditionalFilesInner.");

            if (fileBase64.IsSet && fileBase64.Value == null)
                throw new ArgumentNullException(nameof(fileBase64), "Property is not nullable for class AdditionalFilesInner.");

            return new AdditionalFilesInner(name.Value!, fileUrl, fileBase64);
        }

        /// <summary>
        /// Serializes a <see cref="AdditionalFilesInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="additionalFilesInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, AdditionalFilesInner additionalFilesInner, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, additionalFilesInner, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="AdditionalFilesInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="additionalFilesInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, AdditionalFilesInner additionalFilesInner, JsonSerializerOptions jsonSerializerOptions)
        {
            if (additionalFilesInner.Name == null)
                throw new ArgumentNullException(nameof(additionalFilesInner.Name), "Property is required for class AdditionalFilesInner.");

            if (additionalFilesInner.FileUrlOption.IsSet && additionalFilesInner.FileUrl == null)
                throw new ArgumentNullException(nameof(additionalFilesInner.FileUrl), "Property is required for class AdditionalFilesInner.");

            if (additionalFilesInner.FileBase64Option.IsSet && additionalFilesInner.FileBase64 == null)
                throw new ArgumentNullException(nameof(additionalFilesInner.FileBase64), "Property is required for class AdditionalFilesInner.");

            writer.WriteString("name", additionalFilesInner.Name);

            if (additionalFilesInner.FileUrlOption.IsSet)
                writer.WriteString("file_url", additionalFilesInner.FileUrl);

            if (additionalFilesInner.FileBase64Option.IsSet)
            {
                writer.WritePropertyName("file_base64");
                JsonSerializer.Serialize(writer, additionalFilesInner.FileBase64, jsonSerializerOptions);
            }
        }
    }
}
