// <auto-generated>
/*
 * SignWell Developer API
 *
 * API for creating, managing, and tracking electronic signature workflows.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@signwell.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using SignWell.Sdk.Client;

namespace SignWell.Sdk.Models
{
    /// <summary>
    /// ApiApplicationResponsePreferences
    /// </summary>
    public partial class ApiApplicationResponsePreferences : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ApiApplicationResponsePreferences" /> class.
        /// </summary>
        /// <param name="buttonTextColor">buttonTextColor</param>
        /// <param name="buttonsBorderRadius">buttonsBorderRadius</param>
        /// <param name="customLogoFile">customLogoFile</param>
        /// <param name="linkTextColor">linkTextColor</param>
        /// <param name="primaryColor">primaryColor</param>
        [JsonConstructor]
        public ApiApplicationResponsePreferences(Option<string?> buttonTextColor = default, Option<int?> buttonsBorderRadius = default, Option<string?> customLogoFile = default, Option<string?> linkTextColor = default, Option<string?> primaryColor = default)
        {
            ButtonTextColorOption = buttonTextColor;
            ButtonsBorderRadiusOption = buttonsBorderRadius;
            CustomLogoFileOption = customLogoFile;
            LinkTextColorOption = linkTextColor;
            PrimaryColorOption = primaryColor;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of ButtonTextColor
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ButtonTextColorOption { get; private set; }

        /// <summary>
        /// Gets or Sets ButtonTextColor
        /// </summary>
        [JsonPropertyName("button_text_color")]
        public string? ButtonTextColor { get { return this.ButtonTextColorOption.Value; } set { this.ButtonTextColorOption = new Option<string?>(value); } }

        /// <summary>
        /// Used to track the state of ButtonsBorderRadius
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> ButtonsBorderRadiusOption { get; private set; }

        /// <summary>
        /// Gets or Sets ButtonsBorderRadius
        /// </summary>
        [JsonPropertyName("buttons_border_radius")]
        public int? ButtonsBorderRadius { get { return this.ButtonsBorderRadiusOption.Value; } set { this.ButtonsBorderRadiusOption = new Option<int?>(value); } }

        /// <summary>
        /// Used to track the state of CustomLogoFile
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> CustomLogoFileOption { get; private set; }

        /// <summary>
        /// Gets or Sets CustomLogoFile
        /// </summary>
        [JsonPropertyName("custom_logo_file")]
        public string? CustomLogoFile { get { return this.CustomLogoFileOption.Value; } set { this.CustomLogoFileOption = new Option<string?>(value); } }

        /// <summary>
        /// Used to track the state of LinkTextColor
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> LinkTextColorOption { get; private set; }

        /// <summary>
        /// Gets or Sets LinkTextColor
        /// </summary>
        [JsonPropertyName("link_text_color")]
        public string? LinkTextColor { get { return this.LinkTextColorOption.Value; } set { this.LinkTextColorOption = new Option<string?>(value); } }

        /// <summary>
        /// Used to track the state of PrimaryColor
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> PrimaryColorOption { get; private set; }

        /// <summary>
        /// Gets or Sets PrimaryColor
        /// </summary>
        [JsonPropertyName("primary_color")]
        public string? PrimaryColor { get { return this.PrimaryColorOption.Value; } set { this.PrimaryColorOption = new Option<string?>(value); } }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ApiApplicationResponsePreferences {\n");
            sb.Append("  ButtonTextColor: ").Append(ButtonTextColor).Append("\n");
            sb.Append("  ButtonsBorderRadius: ").Append(ButtonsBorderRadius).Append("\n");
            sb.Append("  CustomLogoFile: ").Append(CustomLogoFile).Append("\n");
            sb.Append("  LinkTextColor: ").Append(LinkTextColor).Append("\n");
            sb.Append("  PrimaryColor: ").Append(PrimaryColor).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ApiApplicationResponsePreferences" />
    /// </summary>
    public class ApiApplicationResponsePreferencesJsonConverter : JsonConverter<ApiApplicationResponsePreferences>
    {
        /// <summary>
        /// Deserializes json to <see cref="ApiApplicationResponsePreferences" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ApiApplicationResponsePreferences Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> buttonTextColor = default;
            Option<int?> buttonsBorderRadius = default;
            Option<string?> customLogoFile = default;
            Option<string?> linkTextColor = default;
            Option<string?> primaryColor = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "button_text_color":
                            buttonTextColor = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "buttons_border_radius":
                            buttonsBorderRadius = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "custom_logo_file":
                            customLogoFile = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "link_text_color":
                            linkTextColor = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "primary_color":
                            primaryColor = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (buttonsBorderRadius.IsSet && buttonsBorderRadius.Value == null)
                throw new ArgumentNullException(nameof(buttonsBorderRadius), "Property is not nullable for class ApiApplicationResponsePreferences.");

            return new ApiApplicationResponsePreferences(buttonTextColor, buttonsBorderRadius, customLogoFile, linkTextColor, primaryColor);
        }

        /// <summary>
        /// Serializes a <see cref="ApiApplicationResponsePreferences" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="apiApplicationResponsePreferences"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ApiApplicationResponsePreferences apiApplicationResponsePreferences, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, apiApplicationResponsePreferences, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ApiApplicationResponsePreferences" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="apiApplicationResponsePreferences"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ApiApplicationResponsePreferences apiApplicationResponsePreferences, JsonSerializerOptions jsonSerializerOptions)
        {
            if (apiApplicationResponsePreferences.ButtonTextColorOption.IsSet)
                if (apiApplicationResponsePreferences.ButtonTextColorOption.Value != null)
                    writer.WriteString("button_text_color", apiApplicationResponsePreferences.ButtonTextColor);
                else
                    writer.WriteNull("button_text_color");

            if (apiApplicationResponsePreferences.ButtonsBorderRadiusOption.IsSet)
                writer.WriteNumber("buttons_border_radius", apiApplicationResponsePreferences.ButtonsBorderRadiusOption.Value!.Value);

            if (apiApplicationResponsePreferences.CustomLogoFileOption.IsSet)
                if (apiApplicationResponsePreferences.CustomLogoFileOption.Value != null)
                    writer.WriteString("custom_logo_file", apiApplicationResponsePreferences.CustomLogoFile);
                else
                    writer.WriteNull("custom_logo_file");

            if (apiApplicationResponsePreferences.LinkTextColorOption.IsSet)
                if (apiApplicationResponsePreferences.LinkTextColorOption.Value != null)
                    writer.WriteString("link_text_color", apiApplicationResponsePreferences.LinkTextColor);
                else
                    writer.WriteNull("link_text_color");

            if (apiApplicationResponsePreferences.PrimaryColorOption.IsSet)
                if (apiApplicationResponsePreferences.PrimaryColorOption.Value != null)
                    writer.WriteString("primary_color", apiApplicationResponsePreferences.PrimaryColor);
                else
                    writer.WriteNull("primary_color");
        }
    }
}
