// <auto-generated>
/*
 * SignWell Developer API
 *
 * API for creating, managing, and tracking electronic signature workflows.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@signwell.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using SignWell.Sdk.Client;

namespace SignWell.Sdk.Models
{
    /// <summary>
    /// API application details
    /// </summary>
    public partial class ApiApplicationResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ApiApplicationResponse" /> class.
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="name">name</param>
        /// <param name="callbackUrls">callbackUrls</param>
        /// <param name="createdAt">createdAt</param>
        /// <param name="updatedAt">updatedAt</param>
        /// <param name="owner">owner</param>
        /// <param name="preferences">preferences</param>
        [JsonConstructor]
        public ApiApplicationResponse(Guid id, string name, Option<List<string>?> callbackUrls = default, Option<DateTimeOffset?> createdAt = default, Option<DateTimeOffset?> updatedAt = default, Option<ApiApplicationResponseOwner?> owner = default, Option<ApiApplicationResponsePreferences?> preferences = default)
        {
            Id = id;
            Name = name;
            CallbackUrlsOption = callbackUrls;
            CreatedAtOption = createdAt;
            UpdatedAtOption = updatedAt;
            OwnerOption = owner;
            PreferencesOption = preferences;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public Guid Id { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [JsonPropertyName("name")]
        public string Name { get; set; }

        /// <summary>
        /// Used to track the state of CallbackUrls
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<string>?> CallbackUrlsOption { get; private set; }

        /// <summary>
        /// Gets or Sets CallbackUrls
        /// </summary>
        [JsonPropertyName("callback_urls")]
        public List<string>? CallbackUrls { get { return this.CallbackUrlsOption.Value; } set { this.CallbackUrlsOption = new Option<List<string>?>(value); } }

        /// <summary>
        /// Used to track the state of CreatedAt
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTimeOffset?> CreatedAtOption { get; private set; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        [JsonPropertyName("created_at")]
        public DateTimeOffset? CreatedAt { get { return this.CreatedAtOption.Value; } set { this.CreatedAtOption = new Option<DateTimeOffset?>(value); } }

        /// <summary>
        /// Used to track the state of UpdatedAt
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTimeOffset?> UpdatedAtOption { get; private set; }

        /// <summary>
        /// Gets or Sets UpdatedAt
        /// </summary>
        [JsonPropertyName("updated_at")]
        public DateTimeOffset? UpdatedAt { get { return this.UpdatedAtOption.Value; } set { this.UpdatedAtOption = new Option<DateTimeOffset?>(value); } }

        /// <summary>
        /// Used to track the state of Owner
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<ApiApplicationResponseOwner?> OwnerOption { get; private set; }

        /// <summary>
        /// Gets or Sets Owner
        /// </summary>
        [JsonPropertyName("owner")]
        public ApiApplicationResponseOwner? Owner { get { return this.OwnerOption.Value; } set { this.OwnerOption = new Option<ApiApplicationResponseOwner?>(value); } }

        /// <summary>
        /// Used to track the state of Preferences
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<ApiApplicationResponsePreferences?> PreferencesOption { get; private set; }

        /// <summary>
        /// Gets or Sets Preferences
        /// </summary>
        [JsonPropertyName("preferences")]
        public ApiApplicationResponsePreferences? Preferences { get { return this.PreferencesOption.Value; } set { this.PreferencesOption = new Option<ApiApplicationResponsePreferences?>(value); } }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ApiApplicationResponse {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  CallbackUrls: ").Append(CallbackUrls).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  UpdatedAt: ").Append(UpdatedAt).Append("\n");
            sb.Append("  Owner: ").Append(Owner).Append("\n");
            sb.Append("  Preferences: ").Append(Preferences).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ApiApplicationResponse" />
    /// </summary>
    public class ApiApplicationResponseJsonConverter : JsonConverter<ApiApplicationResponse>
    {
        /// <summary>
        /// The format to use to serialize CreatedAt
        /// </summary>
        public static string CreatedAtFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize UpdatedAt
        /// </summary>
        public static string UpdatedAtFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="ApiApplicationResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ApiApplicationResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<Guid?> id = default;
            Option<string?> name = default;
            Option<List<string>?> callbackUrls = default;
            Option<DateTimeOffset?> createdAt = default;
            Option<DateTimeOffset?> updatedAt = default;
            Option<ApiApplicationResponseOwner?> owner = default;
            Option<ApiApplicationResponsePreferences?> preferences = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "callback_urls":
                            callbackUrls = new Option<List<string>?>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "created_at":
                            createdAt = new Option<DateTimeOffset?>(JsonSerializer.Deserialize<DateTimeOffset>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "updated_at":
                            updatedAt = new Option<DateTimeOffset?>(JsonSerializer.Deserialize<DateTimeOffset>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "owner":
                            owner = new Option<ApiApplicationResponseOwner?>(JsonSerializer.Deserialize<ApiApplicationResponseOwner>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "preferences":
                            preferences = new Option<ApiApplicationResponsePreferences?>(JsonSerializer.Deserialize<ApiApplicationResponsePreferences>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!id.IsSet)
                throw new ArgumentException("Property is required for class ApiApplicationResponse.", nameof(id));

            if (!name.IsSet)
                throw new ArgumentException("Property is required for class ApiApplicationResponse.", nameof(name));

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class ApiApplicationResponse.");

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class ApiApplicationResponse.");

            if (createdAt.IsSet && createdAt.Value == null)
                throw new ArgumentNullException(nameof(createdAt), "Property is not nullable for class ApiApplicationResponse.");

            if (updatedAt.IsSet && updatedAt.Value == null)
                throw new ArgumentNullException(nameof(updatedAt), "Property is not nullable for class ApiApplicationResponse.");

            if (owner.IsSet && owner.Value == null)
                throw new ArgumentNullException(nameof(owner), "Property is not nullable for class ApiApplicationResponse.");

            if (preferences.IsSet && preferences.Value == null)
                throw new ArgumentNullException(nameof(preferences), "Property is not nullable for class ApiApplicationResponse.");

            return new ApiApplicationResponse(id.Value!.Value!, name.Value!, callbackUrls, createdAt, updatedAt, owner, preferences);
        }

        /// <summary>
        /// Serializes a <see cref="ApiApplicationResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="apiApplicationResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ApiApplicationResponse apiApplicationResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, apiApplicationResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ApiApplicationResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="apiApplicationResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ApiApplicationResponse apiApplicationResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (apiApplicationResponse.Name == null)
                throw new ArgumentNullException(nameof(apiApplicationResponse.Name), "Property is required for class ApiApplicationResponse.");

            if (apiApplicationResponse.OwnerOption.IsSet && apiApplicationResponse.Owner == null)
                throw new ArgumentNullException(nameof(apiApplicationResponse.Owner), "Property is required for class ApiApplicationResponse.");

            if (apiApplicationResponse.PreferencesOption.IsSet && apiApplicationResponse.Preferences == null)
                throw new ArgumentNullException(nameof(apiApplicationResponse.Preferences), "Property is required for class ApiApplicationResponse.");

            writer.WriteString("id", apiApplicationResponse.Id);

            writer.WriteString("name", apiApplicationResponse.Name);

            if (apiApplicationResponse.CallbackUrlsOption.IsSet)
                if (apiApplicationResponse.CallbackUrlsOption.Value != null)
                {
                    writer.WritePropertyName("callback_urls");
                    JsonSerializer.Serialize(writer, apiApplicationResponse.CallbackUrls, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("callback_urls");
            if (apiApplicationResponse.CreatedAtOption.IsSet)
                writer.WriteString("created_at", apiApplicationResponse.CreatedAtOption.Value!.Value.ToString(CreatedAtFormat));

            if (apiApplicationResponse.UpdatedAtOption.IsSet)
                writer.WriteString("updated_at", apiApplicationResponse.UpdatedAtOption.Value!.Value.ToString(UpdatedAtFormat));

            if (apiApplicationResponse.OwnerOption.IsSet)
            {
                writer.WritePropertyName("owner");
                JsonSerializer.Serialize(writer, apiApplicationResponse.Owner, jsonSerializerOptions);
            }
            if (apiApplicationResponse.PreferencesOption.IsSet)
            {
                writer.WritePropertyName("preferences");
                JsonSerializer.Serialize(writer, apiApplicationResponse.Preferences, jsonSerializerOptions);
            }
        }
    }
}
