// <auto-generated>
/*
 * SignWell Developer API
 *
 * API for creating, managing, and tracking electronic signature workflows.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@signwell.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using SignWell.Sdk.Client;

namespace SignWell.Sdk.Models
{
    /// <summary>
    /// Paginated list of documents in a bulk send
    /// </summary>
    public partial class BulkSendDocumentsResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BulkSendDocumentsResponse" /> class.
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="documents">documents</param>
        /// <param name="currentPage">currentPage</param>
        /// <param name="totalCount">totalCount</param>
        /// <param name="totalPages">totalPages</param>
        /// <param name="name">name</param>
        /// <param name="apiApplicationId">apiApplicationId</param>
        /// <param name="createdAt">createdAt</param>
        /// <param name="userId">userId</param>
        /// <param name="status">status</param>
        /// <param name="nextPage">nextPage</param>
        /// <param name="previousPage">previousPage</param>
        [JsonConstructor]
        public BulkSendDocumentsResponse(Guid id, List<DocumentResponse> documents, int currentPage, int totalCount, int totalPages, Option<string?> name = default, Option<Guid?> apiApplicationId = default, Option<DateTimeOffset?> createdAt = default, Option<Guid?> userId = default, Option<string?> status = default, Option<int?> nextPage = default, Option<int?> previousPage = default)
        {
            Id = id;
            Documents = documents;
            CurrentPage = currentPage;
            TotalCount = totalCount;
            TotalPages = totalPages;
            NameOption = name;
            ApiApplicationIdOption = apiApplicationId;
            CreatedAtOption = createdAt;
            UserIdOption = userId;
            StatusOption = status;
            NextPageOption = nextPage;
            PreviousPageOption = previousPage;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public Guid Id { get; set; }

        /// <summary>
        /// Gets or Sets Documents
        /// </summary>
        [JsonPropertyName("documents")]
        public List<DocumentResponse> Documents { get; set; }

        /// <summary>
        /// Gets or Sets CurrentPage
        /// </summary>
        [JsonPropertyName("current_page")]
        public int CurrentPage { get; set; }

        /// <summary>
        /// Gets or Sets TotalCount
        /// </summary>
        [JsonPropertyName("total_count")]
        public int TotalCount { get; set; }

        /// <summary>
        /// Gets or Sets TotalPages
        /// </summary>
        [JsonPropertyName("total_pages")]
        public int TotalPages { get; set; }

        /// <summary>
        /// Used to track the state of Name
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NameOption { get; private set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [JsonPropertyName("name")]
        public string? Name { get { return this.NameOption.Value; } set { this.NameOption = new Option<string?>(value); } }

        /// <summary>
        /// Used to track the state of ApiApplicationId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Guid?> ApiApplicationIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets ApiApplicationId
        /// </summary>
        [JsonPropertyName("api_application_id")]
        public Guid? ApiApplicationId { get { return this.ApiApplicationIdOption.Value; } set { this.ApiApplicationIdOption = new Option<Guid?>(value); } }

        /// <summary>
        /// Used to track the state of CreatedAt
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTimeOffset?> CreatedAtOption { get; private set; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        [JsonPropertyName("created_at")]
        public DateTimeOffset? CreatedAt { get { return this.CreatedAtOption.Value; } set { this.CreatedAtOption = new Option<DateTimeOffset?>(value); } }

        /// <summary>
        /// Used to track the state of UserId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Guid?> UserIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets UserId
        /// </summary>
        [JsonPropertyName("user_id")]
        public Guid? UserId { get { return this.UserIdOption.Value; } set { this.UserIdOption = new Option<Guid?>(value); } }

        /// <summary>
        /// Used to track the state of Status
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> StatusOption { get; private set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [JsonPropertyName("status")]
        public string? Status { get { return this.StatusOption.Value; } set { this.StatusOption = new Option<string?>(value); } }

        /// <summary>
        /// Used to track the state of NextPage
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> NextPageOption { get; private set; }

        /// <summary>
        /// Gets or Sets NextPage
        /// </summary>
        [JsonPropertyName("next_page")]
        public int? NextPage { get { return this.NextPageOption.Value; } set { this.NextPageOption = new Option<int?>(value); } }

        /// <summary>
        /// Used to track the state of PreviousPage
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> PreviousPageOption { get; private set; }

        /// <summary>
        /// Gets or Sets PreviousPage
        /// </summary>
        [JsonPropertyName("previous_page")]
        public int? PreviousPage { get { return this.PreviousPageOption.Value; } set { this.PreviousPageOption = new Option<int?>(value); } }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BulkSendDocumentsResponse {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Documents: ").Append(Documents).Append("\n");
            sb.Append("  CurrentPage: ").Append(CurrentPage).Append("\n");
            sb.Append("  TotalCount: ").Append(TotalCount).Append("\n");
            sb.Append("  TotalPages: ").Append(TotalPages).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  ApiApplicationId: ").Append(ApiApplicationId).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  UserId: ").Append(UserId).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  NextPage: ").Append(NextPage).Append("\n");
            sb.Append("  PreviousPage: ").Append(PreviousPage).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="BulkSendDocumentsResponse" />
    /// </summary>
    public class BulkSendDocumentsResponseJsonConverter : JsonConverter<BulkSendDocumentsResponse>
    {
        /// <summary>
        /// The format to use to serialize CreatedAt
        /// </summary>
        public static string CreatedAtFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="BulkSendDocumentsResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override BulkSendDocumentsResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<Guid?> id = default;
            Option<List<DocumentResponse>?> documents = default;
            Option<int?> currentPage = default;
            Option<int?> totalCount = default;
            Option<int?> totalPages = default;
            Option<string?> name = default;
            Option<Guid?> apiApplicationId = default;
            Option<DateTimeOffset?> createdAt = default;
            Option<Guid?> userId = default;
            Option<string?> status = default;
            Option<int?> nextPage = default;
            Option<int?> previousPage = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "documents":
                            documents = new Option<List<DocumentResponse>?>(JsonSerializer.Deserialize<List<DocumentResponse>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "current_page":
                            currentPage = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "total_count":
                            totalCount = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "total_pages":
                            totalPages = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "api_application_id":
                            apiApplicationId = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "created_at":
                            createdAt = new Option<DateTimeOffset?>(JsonSerializer.Deserialize<DateTimeOffset>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "user_id":
                            userId = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "status":
                            status = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "next_page":
                            nextPage = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "previous_page":
                            previousPage = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!id.IsSet)
                throw new ArgumentException("Property is required for class BulkSendDocumentsResponse.", nameof(id));

            if (!documents.IsSet)
                throw new ArgumentException("Property is required for class BulkSendDocumentsResponse.", nameof(documents));

            if (!currentPage.IsSet)
                throw new ArgumentException("Property is required for class BulkSendDocumentsResponse.", nameof(currentPage));

            if (!totalCount.IsSet)
                throw new ArgumentException("Property is required for class BulkSendDocumentsResponse.", nameof(totalCount));

            if (!totalPages.IsSet)
                throw new ArgumentException("Property is required for class BulkSendDocumentsResponse.", nameof(totalPages));

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class BulkSendDocumentsResponse.");

            if (documents.IsSet && documents.Value == null)
                throw new ArgumentNullException(nameof(documents), "Property is not nullable for class BulkSendDocumentsResponse.");

            if (currentPage.IsSet && currentPage.Value == null)
                throw new ArgumentNullException(nameof(currentPage), "Property is not nullable for class BulkSendDocumentsResponse.");

            if (totalCount.IsSet && totalCount.Value == null)
                throw new ArgumentNullException(nameof(totalCount), "Property is not nullable for class BulkSendDocumentsResponse.");

            if (totalPages.IsSet && totalPages.Value == null)
                throw new ArgumentNullException(nameof(totalPages), "Property is not nullable for class BulkSendDocumentsResponse.");

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class BulkSendDocumentsResponse.");

            if (createdAt.IsSet && createdAt.Value == null)
                throw new ArgumentNullException(nameof(createdAt), "Property is not nullable for class BulkSendDocumentsResponse.");

            if (status.IsSet && status.Value == null)
                throw new ArgumentNullException(nameof(status), "Property is not nullable for class BulkSendDocumentsResponse.");

            return new BulkSendDocumentsResponse(id.Value!.Value!, documents.Value!, currentPage.Value!.Value!, totalCount.Value!.Value!, totalPages.Value!.Value!, name, apiApplicationId, createdAt, userId, status, nextPage, previousPage);
        }

        /// <summary>
        /// Serializes a <see cref="BulkSendDocumentsResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="bulkSendDocumentsResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, BulkSendDocumentsResponse bulkSendDocumentsResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, bulkSendDocumentsResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="BulkSendDocumentsResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="bulkSendDocumentsResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, BulkSendDocumentsResponse bulkSendDocumentsResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (bulkSendDocumentsResponse.Documents == null)
                throw new ArgumentNullException(nameof(bulkSendDocumentsResponse.Documents), "Property is required for class BulkSendDocumentsResponse.");

            if (bulkSendDocumentsResponse.NameOption.IsSet && bulkSendDocumentsResponse.Name == null)
                throw new ArgumentNullException(nameof(bulkSendDocumentsResponse.Name), "Property is required for class BulkSendDocumentsResponse.");

            if (bulkSendDocumentsResponse.StatusOption.IsSet && bulkSendDocumentsResponse.Status == null)
                throw new ArgumentNullException(nameof(bulkSendDocumentsResponse.Status), "Property is required for class BulkSendDocumentsResponse.");

            writer.WriteString("id", bulkSendDocumentsResponse.Id);

            writer.WritePropertyName("documents");
            JsonSerializer.Serialize(writer, bulkSendDocumentsResponse.Documents, jsonSerializerOptions);
            writer.WriteNumber("current_page", bulkSendDocumentsResponse.CurrentPage);

            writer.WriteNumber("total_count", bulkSendDocumentsResponse.TotalCount);

            writer.WriteNumber("total_pages", bulkSendDocumentsResponse.TotalPages);

            if (bulkSendDocumentsResponse.NameOption.IsSet)
                writer.WriteString("name", bulkSendDocumentsResponse.Name);

            if (bulkSendDocumentsResponse.ApiApplicationIdOption.IsSet)
                if (bulkSendDocumentsResponse.ApiApplicationIdOption.Value != null)
                    writer.WriteString("api_application_id", bulkSendDocumentsResponse.ApiApplicationIdOption.Value!.Value);
                else
                    writer.WriteNull("api_application_id");

            if (bulkSendDocumentsResponse.CreatedAtOption.IsSet)
                writer.WriteString("created_at", bulkSendDocumentsResponse.CreatedAtOption.Value!.Value.ToString(CreatedAtFormat));

            if (bulkSendDocumentsResponse.UserIdOption.IsSet)
                if (bulkSendDocumentsResponse.UserIdOption.Value != null)
                    writer.WriteString("user_id", bulkSendDocumentsResponse.UserIdOption.Value!.Value);
                else
                    writer.WriteNull("user_id");

            if (bulkSendDocumentsResponse.StatusOption.IsSet)
                writer.WriteString("status", bulkSendDocumentsResponse.Status);

            if (bulkSendDocumentsResponse.NextPageOption.IsSet)
                if (bulkSendDocumentsResponse.NextPageOption.Value != null)
                    writer.WriteNumber("next_page", bulkSendDocumentsResponse.NextPageOption.Value!.Value);
                else
                    writer.WriteNull("next_page");

            if (bulkSendDocumentsResponse.PreviousPageOption.IsSet)
                if (bulkSendDocumentsResponse.PreviousPageOption.Value != null)
                    writer.WriteNumber("previous_page", bulkSendDocumentsResponse.PreviousPageOption.Value!.Value);
                else
                    writer.WriteNull("previous_page");
        }
    }
}
