// <auto-generated>
/*
 * SignWell Developer API
 *
 * API for creating, managing, and tracking electronic signature workflows.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@signwell.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using SignWell.Sdk.Client;

namespace SignWell.Sdk.Models
{
    /// <summary>
    /// Validated bulk send CSV response with defaults applied
    /// </summary>
    public partial class BulkSendValidateCsvResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BulkSendValidateCsvResponse" /> class.
        /// </summary>
        /// <param name="bulkSendCsv">Base64-encoded CSV content</param>
        /// <param name="templateIds">templateIds</param>
        /// <param name="skipRowErrors">skipRowErrors</param>
        /// <param name="apiApplicationId">apiApplicationId</param>
        /// <param name="name">name</param>
        /// <param name="subject">subject</param>
        /// <param name="message">message</param>
        /// <param name="applySigningOrder">applySigningOrder</param>
        [JsonConstructor]
        public BulkSendValidateCsvResponse(string bulkSendCsv, List<Guid> templateIds, Option<bool?> skipRowErrors = default, Option<Guid?> apiApplicationId = default, Option<string?> name = default, Option<string?> subject = default, Option<string?> message = default, Option<bool?> applySigningOrder = default)
        {
            BulkSendCsv = bulkSendCsv;
            TemplateIds = templateIds;
            SkipRowErrorsOption = skipRowErrors;
            ApiApplicationIdOption = apiApplicationId;
            NameOption = name;
            SubjectOption = subject;
            MessageOption = message;
            ApplySigningOrderOption = applySigningOrder;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Base64-encoded CSV content
        /// </summary>
        /// <value>Base64-encoded CSV content</value>
        [JsonPropertyName("bulk_send_csv")]
        public string BulkSendCsv { get; set; }

        /// <summary>
        /// Gets or Sets TemplateIds
        /// </summary>
        [JsonPropertyName("template_ids")]
        public List<Guid> TemplateIds { get; set; }

        /// <summary>
        /// Used to track the state of SkipRowErrors
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> SkipRowErrorsOption { get; private set; }

        /// <summary>
        /// Gets or Sets SkipRowErrors
        /// </summary>
        [JsonPropertyName("skip_row_errors")]
        public bool? SkipRowErrors { get { return this.SkipRowErrorsOption.Value; } set { this.SkipRowErrorsOption = new Option<bool?>(value); } }

        /// <summary>
        /// Used to track the state of ApiApplicationId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Guid?> ApiApplicationIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets ApiApplicationId
        /// </summary>
        [JsonPropertyName("api_application_id")]
        public Guid? ApiApplicationId { get { return this.ApiApplicationIdOption.Value; } set { this.ApiApplicationIdOption = new Option<Guid?>(value); } }

        /// <summary>
        /// Used to track the state of Name
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NameOption { get; private set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [JsonPropertyName("name")]
        public string? Name { get { return this.NameOption.Value; } set { this.NameOption = new Option<string?>(value); } }

        /// <summary>
        /// Used to track the state of Subject
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> SubjectOption { get; private set; }

        /// <summary>
        /// Gets or Sets Subject
        /// </summary>
        [JsonPropertyName("subject")]
        public string? Subject { get { return this.SubjectOption.Value; } set { this.SubjectOption = new Option<string?>(value); } }

        /// <summary>
        /// Used to track the state of Message
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> MessageOption { get; private set; }

        /// <summary>
        /// Gets or Sets Message
        /// </summary>
        [JsonPropertyName("message")]
        public string? Message { get { return this.MessageOption.Value; } set { this.MessageOption = new Option<string?>(value); } }

        /// <summary>
        /// Used to track the state of ApplySigningOrder
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> ApplySigningOrderOption { get; private set; }

        /// <summary>
        /// Gets or Sets ApplySigningOrder
        /// </summary>
        [JsonPropertyName("apply_signing_order")]
        public bool? ApplySigningOrder { get { return this.ApplySigningOrderOption.Value; } set { this.ApplySigningOrderOption = new Option<bool?>(value); } }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BulkSendValidateCsvResponse {\n");
            sb.Append("  BulkSendCsv: ").Append(BulkSendCsv).Append("\n");
            sb.Append("  TemplateIds: ").Append(TemplateIds).Append("\n");
            sb.Append("  SkipRowErrors: ").Append(SkipRowErrors).Append("\n");
            sb.Append("  ApiApplicationId: ").Append(ApiApplicationId).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Subject: ").Append(Subject).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("  ApplySigningOrder: ").Append(ApplySigningOrder).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="BulkSendValidateCsvResponse" />
    /// </summary>
    public class BulkSendValidateCsvResponseJsonConverter : JsonConverter<BulkSendValidateCsvResponse>
    {
        /// <summary>
        /// Deserializes json to <see cref="BulkSendValidateCsvResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override BulkSendValidateCsvResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> bulkSendCsv = default;
            Option<List<Guid>?> templateIds = default;
            Option<bool?> skipRowErrors = default;
            Option<Guid?> apiApplicationId = default;
            Option<string?> name = default;
            Option<string?> subject = default;
            Option<string?> message = default;
            Option<bool?> applySigningOrder = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "bulk_send_csv":
                            bulkSendCsv = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "template_ids":
                            templateIds = new Option<List<Guid>?>(JsonSerializer.Deserialize<List<Guid>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "skip_row_errors":
                            skipRowErrors = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "api_application_id":
                            apiApplicationId = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "subject":
                            subject = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "message":
                            message = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "apply_signing_order":
                            applySigningOrder = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!bulkSendCsv.IsSet)
                throw new ArgumentException("Property is required for class BulkSendValidateCsvResponse.", nameof(bulkSendCsv));

            if (!templateIds.IsSet)
                throw new ArgumentException("Property is required for class BulkSendValidateCsvResponse.", nameof(templateIds));

            if (bulkSendCsv.IsSet && bulkSendCsv.Value == null)
                throw new ArgumentNullException(nameof(bulkSendCsv), "Property is not nullable for class BulkSendValidateCsvResponse.");

            if (templateIds.IsSet && templateIds.Value == null)
                throw new ArgumentNullException(nameof(templateIds), "Property is not nullable for class BulkSendValidateCsvResponse.");

            if (skipRowErrors.IsSet && skipRowErrors.Value == null)
                throw new ArgumentNullException(nameof(skipRowErrors), "Property is not nullable for class BulkSendValidateCsvResponse.");

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class BulkSendValidateCsvResponse.");

            if (subject.IsSet && subject.Value == null)
                throw new ArgumentNullException(nameof(subject), "Property is not nullable for class BulkSendValidateCsvResponse.");

            if (message.IsSet && message.Value == null)
                throw new ArgumentNullException(nameof(message), "Property is not nullable for class BulkSendValidateCsvResponse.");

            if (applySigningOrder.IsSet && applySigningOrder.Value == null)
                throw new ArgumentNullException(nameof(applySigningOrder), "Property is not nullable for class BulkSendValidateCsvResponse.");

            return new BulkSendValidateCsvResponse(bulkSendCsv.Value!, templateIds.Value!, skipRowErrors, apiApplicationId, name, subject, message, applySigningOrder);
        }

        /// <summary>
        /// Serializes a <see cref="BulkSendValidateCsvResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="bulkSendValidateCsvResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, BulkSendValidateCsvResponse bulkSendValidateCsvResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, bulkSendValidateCsvResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="BulkSendValidateCsvResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="bulkSendValidateCsvResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, BulkSendValidateCsvResponse bulkSendValidateCsvResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (bulkSendValidateCsvResponse.BulkSendCsv == null)
                throw new ArgumentNullException(nameof(bulkSendValidateCsvResponse.BulkSendCsv), "Property is required for class BulkSendValidateCsvResponse.");

            if (bulkSendValidateCsvResponse.TemplateIds == null)
                throw new ArgumentNullException(nameof(bulkSendValidateCsvResponse.TemplateIds), "Property is required for class BulkSendValidateCsvResponse.");

            if (bulkSendValidateCsvResponse.NameOption.IsSet && bulkSendValidateCsvResponse.Name == null)
                throw new ArgumentNullException(nameof(bulkSendValidateCsvResponse.Name), "Property is required for class BulkSendValidateCsvResponse.");

            if (bulkSendValidateCsvResponse.SubjectOption.IsSet && bulkSendValidateCsvResponse.Subject == null)
                throw new ArgumentNullException(nameof(bulkSendValidateCsvResponse.Subject), "Property is required for class BulkSendValidateCsvResponse.");

            if (bulkSendValidateCsvResponse.MessageOption.IsSet && bulkSendValidateCsvResponse.Message == null)
                throw new ArgumentNullException(nameof(bulkSendValidateCsvResponse.Message), "Property is required for class BulkSendValidateCsvResponse.");

            writer.WriteString("bulk_send_csv", bulkSendValidateCsvResponse.BulkSendCsv);

            writer.WritePropertyName("template_ids");
            JsonSerializer.Serialize(writer, bulkSendValidateCsvResponse.TemplateIds, jsonSerializerOptions);
            if (bulkSendValidateCsvResponse.SkipRowErrorsOption.IsSet)
                writer.WriteBoolean("skip_row_errors", bulkSendValidateCsvResponse.SkipRowErrorsOption.Value!.Value);

            if (bulkSendValidateCsvResponse.ApiApplicationIdOption.IsSet)
                if (bulkSendValidateCsvResponse.ApiApplicationIdOption.Value != null)
                    writer.WriteString("api_application_id", bulkSendValidateCsvResponse.ApiApplicationIdOption.Value!.Value);
                else
                    writer.WriteNull("api_application_id");

            if (bulkSendValidateCsvResponse.NameOption.IsSet)
                writer.WriteString("name", bulkSendValidateCsvResponse.Name);

            if (bulkSendValidateCsvResponse.SubjectOption.IsSet)
                writer.WriteString("subject", bulkSendValidateCsvResponse.Subject);

            if (bulkSendValidateCsvResponse.MessageOption.IsSet)
                writer.WriteString("message", bulkSendValidateCsvResponse.Message);

            if (bulkSendValidateCsvResponse.ApplySigningOrderOption.IsSet)
                writer.WriteBoolean("apply_signing_order", bulkSendValidateCsvResponse.ApplySigningOrderOption.Value!.Value);
        }
    }
}
