// <auto-generated>
/*
 * SignWell Developer API
 *
 * API for creating, managing, and tracking electronic signature workflows.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@signwell.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using SignWell.Sdk.Client;

namespace SignWell.Sdk.Models
{
    /// <summary>
    /// DocumentResponse
    /// </summary>
    public partial class DocumentResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DocumentResponse" /> class.
        /// </summary>
        /// <param name="testMode">testMode</param>
        /// <param name="id">id</param>
        /// <param name="apiApplicationId">apiApplicationId</param>
        /// <param name="requesterEmailAddress">requesterEmailAddress</param>
        /// <param name="customRequesterName">customRequesterName</param>
        /// <param name="customRequesterEmail">customRequesterEmail</param>
        /// <param name="name">name</param>
        /// <param name="subject">subject</param>
        /// <param name="message">message</param>
        /// <param name="metadata">metadata</param>
        /// <param name="createdAt">createdAt</param>
        /// <param name="updatedAt">updatedAt</param>
        /// <param name="recipients">recipients</param>
        /// <param name="status">Possible values: Draft, Created, Sending, Sent, Pending, Viewed, Completed, Manually completed, Declined, Canceled, Bounced, Blocked, Error, Expired</param>
        /// <param name="reminders">reminders</param>
        /// <param name="archived">archived</param>
        /// <param name="embeddedSigning">embeddedSigning</param>
        /// <param name="embeddedEditUrl">embeddedEditUrl</param>
        /// <param name="embeddedPreviewUrl">embeddedPreviewUrl</param>
        /// <param name="applySigningOrder">applySigningOrder</param>
        /// <param name="redirectUrl">redirectUrl</param>
        /// <param name="declineRedirectUrl">declineRedirectUrl</param>
        /// <param name="language">language</param>
        /// <param name="expiresIn">expiresIn</param>
        /// <param name="declineMessage">declineMessage</param>
        /// <param name="errorMessage">errorMessage</param>
        /// <param name="templateId">templateId</param>
        /// <param name="templateIds">templateIds</param>
        /// <param name="embeddedSigningNotifications">embeddedSigningNotifications</param>
        /// <param name="attachmentRequests">attachmentRequests</param>
        /// <param name="files">files</param>
        /// <param name="copiedContacts">copiedContacts</param>
        /// <param name="fields">fields</param>
        /// <param name="allowDecline">allowDecline</param>
        /// <param name="allowReassign">allowReassign</param>
        /// <param name="labels">labels</param>
        /// <param name="checkboxGroups">checkboxGroups</param>
        [JsonConstructor]
        public DocumentResponse(bool testMode, Guid id, Option<Guid?> apiApplicationId = default, Option<string?> requesterEmailAddress = default, Option<string?> customRequesterName = default, Option<string?> customRequesterEmail = default, Option<string?> name = default, Option<string?> subject = default, Option<string?> message = default, Option<Dictionary<string, string>?> metadata = default, Option<DateTimeOffset?> createdAt = default, Option<DateTimeOffset?> updatedAt = default, Option<List<DocumentResponseRecipientsInner>?> recipients = default, Option<string?> status = default, Option<bool?> reminders = default, Option<bool?> archived = default, Option<bool?> embeddedSigning = default, Option<string?> embeddedEditUrl = default, Option<string?> embeddedPreviewUrl = default, Option<bool?> applySigningOrder = default, Option<string?> redirectUrl = default, Option<string?> declineRedirectUrl = default, Option<string?> language = default, Option<int?> expiresIn = default, Option<string?> declineMessage = default, Option<string?> errorMessage = default, Option<Guid?> templateId = default, Option<List<Guid>?> templateIds = default, Option<bool?> embeddedSigningNotifications = default, Option<List<DocumentResponseAttachmentRequestsInner>?> attachmentRequests = default, Option<List<FileInfo>?> files = default, Option<List<CopiedContactInfo>?> copiedContacts = default, Option<List<List<DocumentResponseFieldsInnerInner>>?> fields = default, Option<bool?> allowDecline = default, Option<bool?> allowReassign = default, Option<List<LabelInfo>?> labels = default, Option<List<CheckboxGroupInfo>?> checkboxGroups = default)
        {
            TestMode = testMode;
            Id = id;
            ApiApplicationIdOption = apiApplicationId;
            RequesterEmailAddressOption = requesterEmailAddress;
            CustomRequesterNameOption = customRequesterName;
            CustomRequesterEmailOption = customRequesterEmail;
            NameOption = name;
            SubjectOption = subject;
            MessageOption = message;
            MetadataOption = metadata;
            CreatedAtOption = createdAt;
            UpdatedAtOption = updatedAt;
            RecipientsOption = recipients;
            StatusOption = status;
            RemindersOption = reminders;
            ArchivedOption = archived;
            EmbeddedSigningOption = embeddedSigning;
            EmbeddedEditUrlOption = embeddedEditUrl;
            EmbeddedPreviewUrlOption = embeddedPreviewUrl;
            ApplySigningOrderOption = applySigningOrder;
            RedirectUrlOption = redirectUrl;
            DeclineRedirectUrlOption = declineRedirectUrl;
            LanguageOption = language;
            ExpiresInOption = expiresIn;
            DeclineMessageOption = declineMessage;
            ErrorMessageOption = errorMessage;
            TemplateIdOption = templateId;
            TemplateIdsOption = templateIds;
            EmbeddedSigningNotificationsOption = embeddedSigningNotifications;
            AttachmentRequestsOption = attachmentRequests;
            FilesOption = files;
            CopiedContactsOption = copiedContacts;
            FieldsOption = fields;
            AllowDeclineOption = allowDecline;
            AllowReassignOption = allowReassign;
            LabelsOption = labels;
            CheckboxGroupsOption = checkboxGroups;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets TestMode
        /// </summary>
        [JsonPropertyName("test_mode")]
        public bool TestMode { get; set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public Guid Id { get; set; }

        /// <summary>
        /// Used to track the state of ApiApplicationId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Guid?> ApiApplicationIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets ApiApplicationId
        /// </summary>
        [JsonPropertyName("api_application_id")]
        public Guid? ApiApplicationId { get { return this.ApiApplicationIdOption.Value; } set { this.ApiApplicationIdOption = new Option<Guid?>(value); } }

        /// <summary>
        /// Used to track the state of RequesterEmailAddress
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> RequesterEmailAddressOption { get; private set; }

        /// <summary>
        /// Gets or Sets RequesterEmailAddress
        /// </summary>
        [JsonPropertyName("requester_email_address")]
        public string? RequesterEmailAddress { get { return this.RequesterEmailAddressOption.Value; } set { this.RequesterEmailAddressOption = new Option<string?>(value); } }

        /// <summary>
        /// Used to track the state of CustomRequesterName
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> CustomRequesterNameOption { get; private set; }

        /// <summary>
        /// Gets or Sets CustomRequesterName
        /// </summary>
        [JsonPropertyName("custom_requester_name")]
        public string? CustomRequesterName { get { return this.CustomRequesterNameOption.Value; } set { this.CustomRequesterNameOption = new Option<string?>(value); } }

        /// <summary>
        /// Used to track the state of CustomRequesterEmail
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> CustomRequesterEmailOption { get; private set; }

        /// <summary>
        /// Gets or Sets CustomRequesterEmail
        /// </summary>
        [JsonPropertyName("custom_requester_email")]
        public string? CustomRequesterEmail { get { return this.CustomRequesterEmailOption.Value; } set { this.CustomRequesterEmailOption = new Option<string?>(value); } }

        /// <summary>
        /// Used to track the state of Name
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NameOption { get; private set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [JsonPropertyName("name")]
        public string? Name { get { return this.NameOption.Value; } set { this.NameOption = new Option<string?>(value); } }

        /// <summary>
        /// Used to track the state of Subject
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> SubjectOption { get; private set; }

        /// <summary>
        /// Gets or Sets Subject
        /// </summary>
        [JsonPropertyName("subject")]
        public string? Subject { get { return this.SubjectOption.Value; } set { this.SubjectOption = new Option<string?>(value); } }

        /// <summary>
        /// Used to track the state of Message
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> MessageOption { get; private set; }

        /// <summary>
        /// Gets or Sets Message
        /// </summary>
        [JsonPropertyName("message")]
        public string? Message { get { return this.MessageOption.Value; } set { this.MessageOption = new Option<string?>(value); } }

        /// <summary>
        /// Used to track the state of Metadata
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Dictionary<string, string>?> MetadataOption { get; private set; }

        /// <summary>
        /// Gets or Sets Metadata
        /// </summary>
        [JsonPropertyName("metadata")]
        public Dictionary<string, string>? Metadata { get { return this.MetadataOption.Value; } set { this.MetadataOption = new Option<Dictionary<string, string>?>(value); } }

        /// <summary>
        /// Used to track the state of CreatedAt
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTimeOffset?> CreatedAtOption { get; private set; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        [JsonPropertyName("created_at")]
        public DateTimeOffset? CreatedAt { get { return this.CreatedAtOption.Value; } set { this.CreatedAtOption = new Option<DateTimeOffset?>(value); } }

        /// <summary>
        /// Used to track the state of UpdatedAt
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTimeOffset?> UpdatedAtOption { get; private set; }

        /// <summary>
        /// Gets or Sets UpdatedAt
        /// </summary>
        [JsonPropertyName("updated_at")]
        public DateTimeOffset? UpdatedAt { get { return this.UpdatedAtOption.Value; } set { this.UpdatedAtOption = new Option<DateTimeOffset?>(value); } }

        /// <summary>
        /// Used to track the state of Recipients
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<DocumentResponseRecipientsInner>?> RecipientsOption { get; private set; }

        /// <summary>
        /// Gets or Sets Recipients
        /// </summary>
        [JsonPropertyName("recipients")]
        public List<DocumentResponseRecipientsInner>? Recipients { get { return this.RecipientsOption.Value; } set { this.RecipientsOption = new Option<List<DocumentResponseRecipientsInner>?>(value); } }

        /// <summary>
        /// Used to track the state of Status
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> StatusOption { get; private set; }

        /// <summary>
        /// Possible values: Draft, Created, Sending, Sent, Pending, Viewed, Completed, Manually completed, Declined, Canceled, Bounced, Blocked, Error, Expired
        /// </summary>
        /// <value>Possible values: Draft, Created, Sending, Sent, Pending, Viewed, Completed, Manually completed, Declined, Canceled, Bounced, Blocked, Error, Expired</value>
        [JsonPropertyName("status")]
        public string? Status { get { return this.StatusOption.Value; } set { this.StatusOption = new Option<string?>(value); } }

        /// <summary>
        /// Used to track the state of Reminders
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> RemindersOption { get; private set; }

        /// <summary>
        /// Gets or Sets Reminders
        /// </summary>
        [JsonPropertyName("reminders")]
        public bool? Reminders { get { return this.RemindersOption.Value; } set { this.RemindersOption = new Option<bool?>(value); } }

        /// <summary>
        /// Used to track the state of Archived
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> ArchivedOption { get; private set; }

        /// <summary>
        /// Gets or Sets Archived
        /// </summary>
        [JsonPropertyName("archived")]
        public bool? Archived { get { return this.ArchivedOption.Value; } set { this.ArchivedOption = new Option<bool?>(value); } }

        /// <summary>
        /// Used to track the state of EmbeddedSigning
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> EmbeddedSigningOption { get; private set; }

        /// <summary>
        /// Gets or Sets EmbeddedSigning
        /// </summary>
        [JsonPropertyName("embedded_signing")]
        public bool? EmbeddedSigning { get { return this.EmbeddedSigningOption.Value; } set { this.EmbeddedSigningOption = new Option<bool?>(value); } }

        /// <summary>
        /// Used to track the state of EmbeddedEditUrl
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> EmbeddedEditUrlOption { get; private set; }

        /// <summary>
        /// Gets or Sets EmbeddedEditUrl
        /// </summary>
        [JsonPropertyName("embedded_edit_url")]
        public string? EmbeddedEditUrl { get { return this.EmbeddedEditUrlOption.Value; } set { this.EmbeddedEditUrlOption = new Option<string?>(value); } }

        /// <summary>
        /// Used to track the state of EmbeddedPreviewUrl
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> EmbeddedPreviewUrlOption { get; private set; }

        /// <summary>
        /// Gets or Sets EmbeddedPreviewUrl
        /// </summary>
        [JsonPropertyName("embedded_preview_url")]
        public string? EmbeddedPreviewUrl { get { return this.EmbeddedPreviewUrlOption.Value; } set { this.EmbeddedPreviewUrlOption = new Option<string?>(value); } }

        /// <summary>
        /// Used to track the state of ApplySigningOrder
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> ApplySigningOrderOption { get; private set; }

        /// <summary>
        /// Gets or Sets ApplySigningOrder
        /// </summary>
        [JsonPropertyName("apply_signing_order")]
        public bool? ApplySigningOrder { get { return this.ApplySigningOrderOption.Value; } set { this.ApplySigningOrderOption = new Option<bool?>(value); } }

        /// <summary>
        /// Used to track the state of RedirectUrl
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> RedirectUrlOption { get; private set; }

        /// <summary>
        /// Gets or Sets RedirectUrl
        /// </summary>
        [JsonPropertyName("redirect_url")]
        public string? RedirectUrl { get { return this.RedirectUrlOption.Value; } set { this.RedirectUrlOption = new Option<string?>(value); } }

        /// <summary>
        /// Used to track the state of DeclineRedirectUrl
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> DeclineRedirectUrlOption { get; private set; }

        /// <summary>
        /// Gets or Sets DeclineRedirectUrl
        /// </summary>
        [JsonPropertyName("decline_redirect_url")]
        public string? DeclineRedirectUrl { get { return this.DeclineRedirectUrlOption.Value; } set { this.DeclineRedirectUrlOption = new Option<string?>(value); } }

        /// <summary>
        /// Used to track the state of Language
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> LanguageOption { get; private set; }

        /// <summary>
        /// Gets or Sets Language
        /// </summary>
        [JsonPropertyName("language")]
        public string? Language { get { return this.LanguageOption.Value; } set { this.LanguageOption = new Option<string?>(value); } }

        /// <summary>
        /// Used to track the state of ExpiresIn
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> ExpiresInOption { get; private set; }

        /// <summary>
        /// Gets or Sets ExpiresIn
        /// </summary>
        [JsonPropertyName("expires_in")]
        public int? ExpiresIn { get { return this.ExpiresInOption.Value; } set { this.ExpiresInOption = new Option<int?>(value); } }

        /// <summary>
        /// Used to track the state of DeclineMessage
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> DeclineMessageOption { get; private set; }

        /// <summary>
        /// Gets or Sets DeclineMessage
        /// </summary>
        [JsonPropertyName("decline_message")]
        public string? DeclineMessage { get { return this.DeclineMessageOption.Value; } set { this.DeclineMessageOption = new Option<string?>(value); } }

        /// <summary>
        /// Used to track the state of ErrorMessage
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ErrorMessageOption { get; private set; }

        /// <summary>
        /// Gets or Sets ErrorMessage
        /// </summary>
        [JsonPropertyName("error_message")]
        public string? ErrorMessage { get { return this.ErrorMessageOption.Value; } set { this.ErrorMessageOption = new Option<string?>(value); } }

        /// <summary>
        /// Used to track the state of TemplateId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Guid?> TemplateIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets TemplateId
        /// </summary>
        [JsonPropertyName("template_id")]
        public Guid? TemplateId { get { return this.TemplateIdOption.Value; } set { this.TemplateIdOption = new Option<Guid?>(value); } }

        /// <summary>
        /// Used to track the state of TemplateIds
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<Guid>?> TemplateIdsOption { get; private set; }

        /// <summary>
        /// Gets or Sets TemplateIds
        /// </summary>
        [JsonPropertyName("template_ids")]
        public List<Guid>? TemplateIds { get { return this.TemplateIdsOption.Value; } set { this.TemplateIdsOption = new Option<List<Guid>?>(value); } }

        /// <summary>
        /// Used to track the state of EmbeddedSigningNotifications
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> EmbeddedSigningNotificationsOption { get; private set; }

        /// <summary>
        /// Gets or Sets EmbeddedSigningNotifications
        /// </summary>
        [JsonPropertyName("embedded_signing_notifications")]
        public bool? EmbeddedSigningNotifications { get { return this.EmbeddedSigningNotificationsOption.Value; } set { this.EmbeddedSigningNotificationsOption = new Option<bool?>(value); } }

        /// <summary>
        /// Used to track the state of AttachmentRequests
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<DocumentResponseAttachmentRequestsInner>?> AttachmentRequestsOption { get; private set; }

        /// <summary>
        /// Gets or Sets AttachmentRequests
        /// </summary>
        [JsonPropertyName("attachment_requests")]
        public List<DocumentResponseAttachmentRequestsInner>? AttachmentRequests { get { return this.AttachmentRequestsOption.Value; } set { this.AttachmentRequestsOption = new Option<List<DocumentResponseAttachmentRequestsInner>?>(value); } }

        /// <summary>
        /// Used to track the state of Files
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<FileInfo>?> FilesOption { get; private set; }

        /// <summary>
        /// Gets or Sets Files
        /// </summary>
        [JsonPropertyName("files")]
        public List<FileInfo>? Files { get { return this.FilesOption.Value; } set { this.FilesOption = new Option<List<FileInfo>?>(value); } }

        /// <summary>
        /// Used to track the state of CopiedContacts
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<CopiedContactInfo>?> CopiedContactsOption { get; private set; }

        /// <summary>
        /// Gets or Sets CopiedContacts
        /// </summary>
        [JsonPropertyName("copied_contacts")]
        public List<CopiedContactInfo>? CopiedContacts { get { return this.CopiedContactsOption.Value; } set { this.CopiedContactsOption = new Option<List<CopiedContactInfo>?>(value); } }

        /// <summary>
        /// Used to track the state of Fields
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<List<DocumentResponseFieldsInnerInner>>?> FieldsOption { get; private set; }

        /// <summary>
        /// Gets or Sets Fields
        /// </summary>
        [JsonPropertyName("fields")]
        public List<List<DocumentResponseFieldsInnerInner>>? Fields { get { return this.FieldsOption.Value; } set { this.FieldsOption = new Option<List<List<DocumentResponseFieldsInnerInner>>?>(value); } }

        /// <summary>
        /// Used to track the state of AllowDecline
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> AllowDeclineOption { get; private set; }

        /// <summary>
        /// Gets or Sets AllowDecline
        /// </summary>
        [JsonPropertyName("allow_decline")]
        public bool? AllowDecline { get { return this.AllowDeclineOption.Value; } set { this.AllowDeclineOption = new Option<bool?>(value); } }

        /// <summary>
        /// Used to track the state of AllowReassign
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> AllowReassignOption { get; private set; }

        /// <summary>
        /// Gets or Sets AllowReassign
        /// </summary>
        [JsonPropertyName("allow_reassign")]
        public bool? AllowReassign { get { return this.AllowReassignOption.Value; } set { this.AllowReassignOption = new Option<bool?>(value); } }

        /// <summary>
        /// Used to track the state of Labels
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<LabelInfo>?> LabelsOption { get; private set; }

        /// <summary>
        /// Gets or Sets Labels
        /// </summary>
        [JsonPropertyName("labels")]
        public List<LabelInfo>? Labels { get { return this.LabelsOption.Value; } set { this.LabelsOption = new Option<List<LabelInfo>?>(value); } }

        /// <summary>
        /// Used to track the state of CheckboxGroups
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<CheckboxGroupInfo>?> CheckboxGroupsOption { get; private set; }

        /// <summary>
        /// Gets or Sets CheckboxGroups
        /// </summary>
        [JsonPropertyName("checkbox_groups")]
        public List<CheckboxGroupInfo>? CheckboxGroups { get { return this.CheckboxGroupsOption.Value; } set { this.CheckboxGroupsOption = new Option<List<CheckboxGroupInfo>?>(value); } }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DocumentResponse {\n");
            sb.Append("  TestMode: ").Append(TestMode).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  ApiApplicationId: ").Append(ApiApplicationId).Append("\n");
            sb.Append("  RequesterEmailAddress: ").Append(RequesterEmailAddress).Append("\n");
            sb.Append("  CustomRequesterName: ").Append(CustomRequesterName).Append("\n");
            sb.Append("  CustomRequesterEmail: ").Append(CustomRequesterEmail).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Subject: ").Append(Subject).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("  Metadata: ").Append(Metadata).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  UpdatedAt: ").Append(UpdatedAt).Append("\n");
            sb.Append("  Recipients: ").Append(Recipients).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  Reminders: ").Append(Reminders).Append("\n");
            sb.Append("  Archived: ").Append(Archived).Append("\n");
            sb.Append("  EmbeddedSigning: ").Append(EmbeddedSigning).Append("\n");
            sb.Append("  EmbeddedEditUrl: ").Append(EmbeddedEditUrl).Append("\n");
            sb.Append("  EmbeddedPreviewUrl: ").Append(EmbeddedPreviewUrl).Append("\n");
            sb.Append("  ApplySigningOrder: ").Append(ApplySigningOrder).Append("\n");
            sb.Append("  RedirectUrl: ").Append(RedirectUrl).Append("\n");
            sb.Append("  DeclineRedirectUrl: ").Append(DeclineRedirectUrl).Append("\n");
            sb.Append("  Language: ").Append(Language).Append("\n");
            sb.Append("  ExpiresIn: ").Append(ExpiresIn).Append("\n");
            sb.Append("  DeclineMessage: ").Append(DeclineMessage).Append("\n");
            sb.Append("  ErrorMessage: ").Append(ErrorMessage).Append("\n");
            sb.Append("  TemplateId: ").Append(TemplateId).Append("\n");
            sb.Append("  TemplateIds: ").Append(TemplateIds).Append("\n");
            sb.Append("  EmbeddedSigningNotifications: ").Append(EmbeddedSigningNotifications).Append("\n");
            sb.Append("  AttachmentRequests: ").Append(AttachmentRequests).Append("\n");
            sb.Append("  Files: ").Append(Files).Append("\n");
            sb.Append("  CopiedContacts: ").Append(CopiedContacts).Append("\n");
            sb.Append("  Fields: ").Append(Fields).Append("\n");
            sb.Append("  AllowDecline: ").Append(AllowDecline).Append("\n");
            sb.Append("  AllowReassign: ").Append(AllowReassign).Append("\n");
            sb.Append("  Labels: ").Append(Labels).Append("\n");
            sb.Append("  CheckboxGroups: ").Append(CheckboxGroups).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="DocumentResponse" />
    /// </summary>
    public class DocumentResponseJsonConverter : JsonConverter<DocumentResponse>
    {
        /// <summary>
        /// The format to use to serialize CreatedAt
        /// </summary>
        public static string CreatedAtFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize UpdatedAt
        /// </summary>
        public static string UpdatedAtFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="DocumentResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override DocumentResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<bool?> testMode = default;
            Option<Guid?> id = default;
            Option<Guid?> apiApplicationId = default;
            Option<string?> requesterEmailAddress = default;
            Option<string?> customRequesterName = default;
            Option<string?> customRequesterEmail = default;
            Option<string?> name = default;
            Option<string?> subject = default;
            Option<string?> message = default;
            Option<Dictionary<string, string>?> metadata = default;
            Option<DateTimeOffset?> createdAt = default;
            Option<DateTimeOffset?> updatedAt = default;
            Option<List<DocumentResponseRecipientsInner>?> recipients = default;
            Option<string?> status = default;
            Option<bool?> reminders = default;
            Option<bool?> archived = default;
            Option<bool?> embeddedSigning = default;
            Option<string?> embeddedEditUrl = default;
            Option<string?> embeddedPreviewUrl = default;
            Option<bool?> applySigningOrder = default;
            Option<string?> redirectUrl = default;
            Option<string?> declineRedirectUrl = default;
            Option<string?> language = default;
            Option<int?> expiresIn = default;
            Option<string?> declineMessage = default;
            Option<string?> errorMessage = default;
            Option<Guid?> templateId = default;
            Option<List<Guid>?> templateIds = default;
            Option<bool?> embeddedSigningNotifications = default;
            Option<List<DocumentResponseAttachmentRequestsInner>?> attachmentRequests = default;
            Option<List<FileInfo>?> files = default;
            Option<List<CopiedContactInfo>?> copiedContacts = default;
            Option<List<List<DocumentResponseFieldsInnerInner>>?> fields = default;
            Option<bool?> allowDecline = default;
            Option<bool?> allowReassign = default;
            Option<List<LabelInfo>?> labels = default;
            Option<List<CheckboxGroupInfo>?> checkboxGroups = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "test_mode":
                            testMode = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "id":
                            id = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "api_application_id":
                            apiApplicationId = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "requester_email_address":
                            requesterEmailAddress = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "custom_requester_name":
                            customRequesterName = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "custom_requester_email":
                            customRequesterEmail = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "subject":
                            subject = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "message":
                            message = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "metadata":
                            metadata = new Option<Dictionary<string, string>?>(JsonSerializer.Deserialize<Dictionary<string, string>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "created_at":
                            createdAt = new Option<DateTimeOffset?>(JsonSerializer.Deserialize<DateTimeOffset>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "updated_at":
                            updatedAt = new Option<DateTimeOffset?>(JsonSerializer.Deserialize<DateTimeOffset>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "recipients":
                            recipients = new Option<List<DocumentResponseRecipientsInner>?>(JsonSerializer.Deserialize<List<DocumentResponseRecipientsInner>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "status":
                            status = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "reminders":
                            reminders = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "archived":
                            archived = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "embedded_signing":
                            embeddedSigning = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "embedded_edit_url":
                            embeddedEditUrl = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "embedded_preview_url":
                            embeddedPreviewUrl = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "apply_signing_order":
                            applySigningOrder = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "redirect_url":
                            redirectUrl = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "decline_redirect_url":
                            declineRedirectUrl = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "language":
                            language = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "expires_in":
                            expiresIn = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "decline_message":
                            declineMessage = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "error_message":
                            errorMessage = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "template_id":
                            templateId = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "template_ids":
                            templateIds = new Option<List<Guid>?>(JsonSerializer.Deserialize<List<Guid>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "embedded_signing_notifications":
                            embeddedSigningNotifications = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "attachment_requests":
                            attachmentRequests = new Option<List<DocumentResponseAttachmentRequestsInner>?>(JsonSerializer.Deserialize<List<DocumentResponseAttachmentRequestsInner>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "files":
                            files = new Option<List<FileInfo>?>(JsonSerializer.Deserialize<List<FileInfo>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "copied_contacts":
                            copiedContacts = new Option<List<CopiedContactInfo>?>(JsonSerializer.Deserialize<List<CopiedContactInfo>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "fields":
                            fields = new Option<List<List<DocumentResponseFieldsInnerInner>>?>(JsonSerializer.Deserialize<List<List<DocumentResponseFieldsInnerInner>>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "allow_decline":
                            allowDecline = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "allow_reassign":
                            allowReassign = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "labels":
                            labels = new Option<List<LabelInfo>?>(JsonSerializer.Deserialize<List<LabelInfo>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "checkbox_groups":
                            checkboxGroups = new Option<List<CheckboxGroupInfo>?>(JsonSerializer.Deserialize<List<CheckboxGroupInfo>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!testMode.IsSet)
                throw new ArgumentException("Property is required for class DocumentResponse.", nameof(testMode));

            if (!id.IsSet)
                throw new ArgumentException("Property is required for class DocumentResponse.", nameof(id));

            if (testMode.IsSet && testMode.Value == null)
                throw new ArgumentNullException(nameof(testMode), "Property is not nullable for class DocumentResponse.");

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class DocumentResponse.");

            if (requesterEmailAddress.IsSet && requesterEmailAddress.Value == null)
                throw new ArgumentNullException(nameof(requesterEmailAddress), "Property is not nullable for class DocumentResponse.");

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class DocumentResponse.");

            if (subject.IsSet && subject.Value == null)
                throw new ArgumentNullException(nameof(subject), "Property is not nullable for class DocumentResponse.");

            if (message.IsSet && message.Value == null)
                throw new ArgumentNullException(nameof(message), "Property is not nullable for class DocumentResponse.");

            if (createdAt.IsSet && createdAt.Value == null)
                throw new ArgumentNullException(nameof(createdAt), "Property is not nullable for class DocumentResponse.");

            if (updatedAt.IsSet && updatedAt.Value == null)
                throw new ArgumentNullException(nameof(updatedAt), "Property is not nullable for class DocumentResponse.");

            if (recipients.IsSet && recipients.Value == null)
                throw new ArgumentNullException(nameof(recipients), "Property is not nullable for class DocumentResponse.");

            if (status.IsSet && status.Value == null)
                throw new ArgumentNullException(nameof(status), "Property is not nullable for class DocumentResponse.");

            if (reminders.IsSet && reminders.Value == null)
                throw new ArgumentNullException(nameof(reminders), "Property is not nullable for class DocumentResponse.");

            if (archived.IsSet && archived.Value == null)
                throw new ArgumentNullException(nameof(archived), "Property is not nullable for class DocumentResponse.");

            if (embeddedSigning.IsSet && embeddedSigning.Value == null)
                throw new ArgumentNullException(nameof(embeddedSigning), "Property is not nullable for class DocumentResponse.");

            if (applySigningOrder.IsSet && applySigningOrder.Value == null)
                throw new ArgumentNullException(nameof(applySigningOrder), "Property is not nullable for class DocumentResponse.");

            if (language.IsSet && language.Value == null)
                throw new ArgumentNullException(nameof(language), "Property is not nullable for class DocumentResponse.");

            if (expiresIn.IsSet && expiresIn.Value == null)
                throw new ArgumentNullException(nameof(expiresIn), "Property is not nullable for class DocumentResponse.");

            if (templateIds.IsSet && templateIds.Value == null)
                throw new ArgumentNullException(nameof(templateIds), "Property is not nullable for class DocumentResponse.");

            if (embeddedSigningNotifications.IsSet && embeddedSigningNotifications.Value == null)
                throw new ArgumentNullException(nameof(embeddedSigningNotifications), "Property is not nullable for class DocumentResponse.");

            if (attachmentRequests.IsSet && attachmentRequests.Value == null)
                throw new ArgumentNullException(nameof(attachmentRequests), "Property is not nullable for class DocumentResponse.");

            if (files.IsSet && files.Value == null)
                throw new ArgumentNullException(nameof(files), "Property is not nullable for class DocumentResponse.");

            if (copiedContacts.IsSet && copiedContacts.Value == null)
                throw new ArgumentNullException(nameof(copiedContacts), "Property is not nullable for class DocumentResponse.");

            if (fields.IsSet && fields.Value == null)
                throw new ArgumentNullException(nameof(fields), "Property is not nullable for class DocumentResponse.");

            if (labels.IsSet && labels.Value == null)
                throw new ArgumentNullException(nameof(labels), "Property is not nullable for class DocumentResponse.");

            if (checkboxGroups.IsSet && checkboxGroups.Value == null)
                throw new ArgumentNullException(nameof(checkboxGroups), "Property is not nullable for class DocumentResponse.");

            return new DocumentResponse(testMode.Value!.Value!, id.Value!.Value!, apiApplicationId, requesterEmailAddress, customRequesterName, customRequesterEmail, name, subject, message, metadata, createdAt, updatedAt, recipients, status, reminders, archived, embeddedSigning, embeddedEditUrl, embeddedPreviewUrl, applySigningOrder, redirectUrl, declineRedirectUrl, language, expiresIn, declineMessage, errorMessage, templateId, templateIds, embeddedSigningNotifications, attachmentRequests, files, copiedContacts, fields, allowDecline, allowReassign, labels, checkboxGroups);
        }

        /// <summary>
        /// Serializes a <see cref="DocumentResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="documentResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, DocumentResponse documentResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, documentResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="DocumentResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="documentResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, DocumentResponse documentResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (documentResponse.RequesterEmailAddressOption.IsSet && documentResponse.RequesterEmailAddress == null)
                throw new ArgumentNullException(nameof(documentResponse.RequesterEmailAddress), "Property is required for class DocumentResponse.");

            if (documentResponse.NameOption.IsSet && documentResponse.Name == null)
                throw new ArgumentNullException(nameof(documentResponse.Name), "Property is required for class DocumentResponse.");

            if (documentResponse.SubjectOption.IsSet && documentResponse.Subject == null)
                throw new ArgumentNullException(nameof(documentResponse.Subject), "Property is required for class DocumentResponse.");

            if (documentResponse.MessageOption.IsSet && documentResponse.Message == null)
                throw new ArgumentNullException(nameof(documentResponse.Message), "Property is required for class DocumentResponse.");

            if (documentResponse.RecipientsOption.IsSet && documentResponse.Recipients == null)
                throw new ArgumentNullException(nameof(documentResponse.Recipients), "Property is required for class DocumentResponse.");

            if (documentResponse.StatusOption.IsSet && documentResponse.Status == null)
                throw new ArgumentNullException(nameof(documentResponse.Status), "Property is required for class DocumentResponse.");

            if (documentResponse.LanguageOption.IsSet && documentResponse.Language == null)
                throw new ArgumentNullException(nameof(documentResponse.Language), "Property is required for class DocumentResponse.");

            if (documentResponse.TemplateIdsOption.IsSet && documentResponse.TemplateIds == null)
                throw new ArgumentNullException(nameof(documentResponse.TemplateIds), "Property is required for class DocumentResponse.");

            if (documentResponse.AttachmentRequestsOption.IsSet && documentResponse.AttachmentRequests == null)
                throw new ArgumentNullException(nameof(documentResponse.AttachmentRequests), "Property is required for class DocumentResponse.");

            if (documentResponse.FilesOption.IsSet && documentResponse.Files == null)
                throw new ArgumentNullException(nameof(documentResponse.Files), "Property is required for class DocumentResponse.");

            if (documentResponse.CopiedContactsOption.IsSet && documentResponse.CopiedContacts == null)
                throw new ArgumentNullException(nameof(documentResponse.CopiedContacts), "Property is required for class DocumentResponse.");

            if (documentResponse.FieldsOption.IsSet && documentResponse.Fields == null)
                throw new ArgumentNullException(nameof(documentResponse.Fields), "Property is required for class DocumentResponse.");

            if (documentResponse.LabelsOption.IsSet && documentResponse.Labels == null)
                throw new ArgumentNullException(nameof(documentResponse.Labels), "Property is required for class DocumentResponse.");

            if (documentResponse.CheckboxGroupsOption.IsSet && documentResponse.CheckboxGroups == null)
                throw new ArgumentNullException(nameof(documentResponse.CheckboxGroups), "Property is required for class DocumentResponse.");

            writer.WriteBoolean("test_mode", documentResponse.TestMode);

            writer.WriteString("id", documentResponse.Id);

            if (documentResponse.ApiApplicationIdOption.IsSet)
                if (documentResponse.ApiApplicationIdOption.Value != null)
                    writer.WriteString("api_application_id", documentResponse.ApiApplicationIdOption.Value!.Value);
                else
                    writer.WriteNull("api_application_id");

            if (documentResponse.RequesterEmailAddressOption.IsSet)
                writer.WriteString("requester_email_address", documentResponse.RequesterEmailAddress);

            if (documentResponse.CustomRequesterNameOption.IsSet)
                if (documentResponse.CustomRequesterNameOption.Value != null)
                    writer.WriteString("custom_requester_name", documentResponse.CustomRequesterName);
                else
                    writer.WriteNull("custom_requester_name");

            if (documentResponse.CustomRequesterEmailOption.IsSet)
                if (documentResponse.CustomRequesterEmailOption.Value != null)
                    writer.WriteString("custom_requester_email", documentResponse.CustomRequesterEmail);
                else
                    writer.WriteNull("custom_requester_email");

            if (documentResponse.NameOption.IsSet)
                writer.WriteString("name", documentResponse.Name);

            if (documentResponse.SubjectOption.IsSet)
                writer.WriteString("subject", documentResponse.Subject);

            if (documentResponse.MessageOption.IsSet)
                writer.WriteString("message", documentResponse.Message);

            if (documentResponse.MetadataOption.IsSet)
                if (documentResponse.MetadataOption.Value != null)
                {
                    writer.WritePropertyName("metadata");
                    JsonSerializer.Serialize(writer, documentResponse.Metadata, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("metadata");
            if (documentResponse.CreatedAtOption.IsSet)
                writer.WriteString("created_at", documentResponse.CreatedAtOption.Value!.Value.ToString(CreatedAtFormat));

            if (documentResponse.UpdatedAtOption.IsSet)
                writer.WriteString("updated_at", documentResponse.UpdatedAtOption.Value!.Value.ToString(UpdatedAtFormat));

            if (documentResponse.RecipientsOption.IsSet)
            {
                writer.WritePropertyName("recipients");
                JsonSerializer.Serialize(writer, documentResponse.Recipients, jsonSerializerOptions);
            }
            if (documentResponse.StatusOption.IsSet)
                writer.WriteString("status", documentResponse.Status);

            if (documentResponse.RemindersOption.IsSet)
                writer.WriteBoolean("reminders", documentResponse.RemindersOption.Value!.Value);

            if (documentResponse.ArchivedOption.IsSet)
                writer.WriteBoolean("archived", documentResponse.ArchivedOption.Value!.Value);

            if (documentResponse.EmbeddedSigningOption.IsSet)
                writer.WriteBoolean("embedded_signing", documentResponse.EmbeddedSigningOption.Value!.Value);

            if (documentResponse.EmbeddedEditUrlOption.IsSet)
                if (documentResponse.EmbeddedEditUrlOption.Value != null)
                    writer.WriteString("embedded_edit_url", documentResponse.EmbeddedEditUrl);
                else
                    writer.WriteNull("embedded_edit_url");

            if (documentResponse.EmbeddedPreviewUrlOption.IsSet)
                if (documentResponse.EmbeddedPreviewUrlOption.Value != null)
                    writer.WriteString("embedded_preview_url", documentResponse.EmbeddedPreviewUrl);
                else
                    writer.WriteNull("embedded_preview_url");

            if (documentResponse.ApplySigningOrderOption.IsSet)
                writer.WriteBoolean("apply_signing_order", documentResponse.ApplySigningOrderOption.Value!.Value);

            if (documentResponse.RedirectUrlOption.IsSet)
                if (documentResponse.RedirectUrlOption.Value != null)
                    writer.WriteString("redirect_url", documentResponse.RedirectUrl);
                else
                    writer.WriteNull("redirect_url");

            if (documentResponse.DeclineRedirectUrlOption.IsSet)
                if (documentResponse.DeclineRedirectUrlOption.Value != null)
                    writer.WriteString("decline_redirect_url", documentResponse.DeclineRedirectUrl);
                else
                    writer.WriteNull("decline_redirect_url");

            if (documentResponse.LanguageOption.IsSet)
                writer.WriteString("language", documentResponse.Language);

            if (documentResponse.ExpiresInOption.IsSet)
                writer.WriteNumber("expires_in", documentResponse.ExpiresInOption.Value!.Value);

            if (documentResponse.DeclineMessageOption.IsSet)
                if (documentResponse.DeclineMessageOption.Value != null)
                    writer.WriteString("decline_message", documentResponse.DeclineMessage);
                else
                    writer.WriteNull("decline_message");

            if (documentResponse.ErrorMessageOption.IsSet)
                if (documentResponse.ErrorMessageOption.Value != null)
                    writer.WriteString("error_message", documentResponse.ErrorMessage);
                else
                    writer.WriteNull("error_message");

            if (documentResponse.TemplateIdOption.IsSet)
                if (documentResponse.TemplateIdOption.Value != null)
                    writer.WriteString("template_id", documentResponse.TemplateIdOption.Value!.Value);
                else
                    writer.WriteNull("template_id");

            if (documentResponse.TemplateIdsOption.IsSet)
            {
                writer.WritePropertyName("template_ids");
                JsonSerializer.Serialize(writer, documentResponse.TemplateIds, jsonSerializerOptions);
            }
            if (documentResponse.EmbeddedSigningNotificationsOption.IsSet)
                writer.WriteBoolean("embedded_signing_notifications", documentResponse.EmbeddedSigningNotificationsOption.Value!.Value);

            if (documentResponse.AttachmentRequestsOption.IsSet)
            {
                writer.WritePropertyName("attachment_requests");
                JsonSerializer.Serialize(writer, documentResponse.AttachmentRequests, jsonSerializerOptions);
            }
            if (documentResponse.FilesOption.IsSet)
            {
                writer.WritePropertyName("files");
                JsonSerializer.Serialize(writer, documentResponse.Files, jsonSerializerOptions);
            }
            if (documentResponse.CopiedContactsOption.IsSet)
            {
                writer.WritePropertyName("copied_contacts");
                JsonSerializer.Serialize(writer, documentResponse.CopiedContacts, jsonSerializerOptions);
            }
            if (documentResponse.FieldsOption.IsSet)
            {
                writer.WritePropertyName("fields");
                JsonSerializer.Serialize(writer, documentResponse.Fields, jsonSerializerOptions);
            }
            if (documentResponse.AllowDeclineOption.IsSet)
                if (documentResponse.AllowDeclineOption.Value != null)
                    writer.WriteBoolean("allow_decline", documentResponse.AllowDeclineOption.Value!.Value);
                else
                    writer.WriteNull("allow_decline");

            if (documentResponse.AllowReassignOption.IsSet)
                if (documentResponse.AllowReassignOption.Value != null)
                    writer.WriteBoolean("allow_reassign", documentResponse.AllowReassignOption.Value!.Value);
                else
                    writer.WriteNull("allow_reassign");

            if (documentResponse.LabelsOption.IsSet)
            {
                writer.WritePropertyName("labels");
                JsonSerializer.Serialize(writer, documentResponse.Labels, jsonSerializerOptions);
            }
            if (documentResponse.CheckboxGroupsOption.IsSet)
            {
                writer.WritePropertyName("checkbox_groups");
                JsonSerializer.Serialize(writer, documentResponse.CheckboxGroups, jsonSerializerOptions);
            }
        }
    }
}
