// <auto-generated>
/*
 * SignWell Developer API
 *
 * API for creating, managing, and tracking electronic signature workflows.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@signwell.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using SignWell.Sdk.Client;

namespace SignWell.Sdk.Models
{
    /// <summary>
    /// DocumentTemplateUpdateRequest
    /// </summary>
    public partial class DocumentTemplateUpdateRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DocumentTemplateUpdateRequest" /> class.
        /// </summary>
        /// <param name="name">The name of the template.</param>
        /// <param name="subject">Email subject for the signature request that recipients will see. Defaults to the default system subject or a template subject (if the document is created from a template).</param>
        /// <param name="message">Email message for the signature request that recipients will see. Defaults to the default system message or a template message (if the document is created from a template).</param>
        /// <param name="draft">Whether the template can still be updated before it is ready for usage. If set to &#x60;false&#x60; the template is marked as &#x60;Available&#x60; and it will be ready for use. Defaults to &#x60;false&#x60;. (default to false)</param>
        /// <param name="expiresIn">Number of days before the signature request expires. Defaults to the account expiration setting or template expiration (if the document is created from a template).</param>
        /// <param name="reminders">Whether to send signing reminders to recipients. Reminders are sent on day 3, day 6, and day 10 if set to &#x60;true&#x60;. Defaults to &#x60;true&#x60;. (default to true)</param>
        /// <param name="applySigningOrder">When set to &#x60;true&#x60; recipients will sign one at a time in the order of the &#x60;recipients&#x60; collection of this request. (default to false)</param>
        /// <param name="apiApplicationId">Unique identifier for API Application settings to use. API Applications are optional and mainly used when isolating OAuth apps or for more control over embedded API settings</param>
        /// <param name="redirectUrl">A URL that recipients are redirected to after successfully signing a document.</param>
        /// <param name="allowDecline">Whether to allow recipients the option to decline signing a document. If multiple signers are involved in a document, any single recipient can cancel the entire document signing process by declining to sign. (default to true)</param>
        /// <param name="allowReassign">In some cases a signer is not the right person to sign and may need to reassign their signing responsibilities to another person. This feature allows them to reassign the document to someone else. (default to true)</param>
        /// <param name="declineRedirectUrl">A URL that recipients are redirected to if the document is declined.</param>
        /// <param name="metadata">Optional key-value data that can be associated with the document. If set, will be available every time the document data is returned.</param>
        /// <param name="labels">Labels can be used to organize documents in a way that can make it easy to find using the document search in SignWell. A document can have multiple labels. Updating labels on a document will replace any existing labels for that document.</param>
        /// <param name="checkboxGroups">Checkbox fields that are placed on a document can be grouped with selection requirements. At least 2 checkbox fields in an array of fields must be assigned to the same recipient.</param>
        [JsonConstructor]
        public DocumentTemplateUpdateRequest(Option<string?> name = default, Option<string?> subject = default, Option<string?> message = default, Option<bool?> draft = default, Option<int?> expiresIn = default, Option<bool?> reminders = default, Option<bool?> applySigningOrder = default, Option<Guid?> apiApplicationId = default, Option<string?> redirectUrl = default, Option<bool?> allowDecline = default, Option<bool?> allowReassign = default, Option<string?> declineRedirectUrl = default, Option<Dictionary<string, string>?> metadata = default, Option<List<LabelRequest>?> labels = default, Option<List<TemplateCheckboxGroupsInner>?> checkboxGroups = default)
        {
            NameOption = name;
            SubjectOption = subject;
            MessageOption = message;
            DraftOption = draft;
            ExpiresInOption = expiresIn;
            RemindersOption = reminders;
            ApplySigningOrderOption = applySigningOrder;
            ApiApplicationIdOption = apiApplicationId;
            RedirectUrlOption = redirectUrl;
            AllowDeclineOption = allowDecline;
            AllowReassignOption = allowReassign;
            DeclineRedirectUrlOption = declineRedirectUrl;
            MetadataOption = metadata;
            LabelsOption = labels;
            CheckboxGroupsOption = checkboxGroups;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Name
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NameOption { get; private set; }

        /// <summary>
        /// The name of the template.
        /// </summary>
        /// <value>The name of the template.</value>
        [JsonPropertyName("name")]
        public string? Name { get { return this.NameOption.Value; } set { this.NameOption = new Option<string?>(value); } }

        /// <summary>
        /// Used to track the state of Subject
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> SubjectOption { get; private set; }

        /// <summary>
        /// Email subject for the signature request that recipients will see. Defaults to the default system subject or a template subject (if the document is created from a template).
        /// </summary>
        /// <value>Email subject for the signature request that recipients will see. Defaults to the default system subject or a template subject (if the document is created from a template).</value>
        [JsonPropertyName("subject")]
        public string? Subject { get { return this.SubjectOption.Value; } set { this.SubjectOption = new Option<string?>(value); } }

        /// <summary>
        /// Used to track the state of Message
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> MessageOption { get; private set; }

        /// <summary>
        /// Email message for the signature request that recipients will see. Defaults to the default system message or a template message (if the document is created from a template).
        /// </summary>
        /// <value>Email message for the signature request that recipients will see. Defaults to the default system message or a template message (if the document is created from a template).</value>
        [JsonPropertyName("message")]
        public string? Message { get { return this.MessageOption.Value; } set { this.MessageOption = new Option<string?>(value); } }

        /// <summary>
        /// Used to track the state of Draft
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> DraftOption { get; private set; }

        /// <summary>
        /// Whether the template can still be updated before it is ready for usage. If set to &#x60;false&#x60; the template is marked as &#x60;Available&#x60; and it will be ready for use. Defaults to &#x60;false&#x60;.
        /// </summary>
        /// <value>Whether the template can still be updated before it is ready for usage. If set to &#x60;false&#x60; the template is marked as &#x60;Available&#x60; and it will be ready for use. Defaults to &#x60;false&#x60;.</value>
        [JsonPropertyName("draft")]
        public bool? Draft { get { return this.DraftOption.Value; } set { this.DraftOption = new Option<bool?>(value); } }

        /// <summary>
        /// Used to track the state of ExpiresIn
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> ExpiresInOption { get; private set; }

        /// <summary>
        /// Number of days before the signature request expires. Defaults to the account expiration setting or template expiration (if the document is created from a template).
        /// </summary>
        /// <value>Number of days before the signature request expires. Defaults to the account expiration setting or template expiration (if the document is created from a template).</value>
        [JsonPropertyName("expires_in")]
        public int? ExpiresIn { get { return this.ExpiresInOption.Value; } set { this.ExpiresInOption = new Option<int?>(value); } }

        /// <summary>
        /// Used to track the state of Reminders
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> RemindersOption { get; private set; }

        /// <summary>
        /// Whether to send signing reminders to recipients. Reminders are sent on day 3, day 6, and day 10 if set to &#x60;true&#x60;. Defaults to &#x60;true&#x60;.
        /// </summary>
        /// <value>Whether to send signing reminders to recipients. Reminders are sent on day 3, day 6, and day 10 if set to &#x60;true&#x60;. Defaults to &#x60;true&#x60;.</value>
        [JsonPropertyName("reminders")]
        public bool? Reminders { get { return this.RemindersOption.Value; } set { this.RemindersOption = new Option<bool?>(value); } }

        /// <summary>
        /// Used to track the state of ApplySigningOrder
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> ApplySigningOrderOption { get; private set; }

        /// <summary>
        /// When set to &#x60;true&#x60; recipients will sign one at a time in the order of the &#x60;recipients&#x60; collection of this request.
        /// </summary>
        /// <value>When set to &#x60;true&#x60; recipients will sign one at a time in the order of the &#x60;recipients&#x60; collection of this request.</value>
        [JsonPropertyName("apply_signing_order")]
        public bool? ApplySigningOrder { get { return this.ApplySigningOrderOption.Value; } set { this.ApplySigningOrderOption = new Option<bool?>(value); } }

        /// <summary>
        /// Used to track the state of ApiApplicationId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Guid?> ApiApplicationIdOption { get; private set; }

        /// <summary>
        /// Unique identifier for API Application settings to use. API Applications are optional and mainly used when isolating OAuth apps or for more control over embedded API settings
        /// </summary>
        /// <value>Unique identifier for API Application settings to use. API Applications are optional and mainly used when isolating OAuth apps or for more control over embedded API settings</value>
        [JsonPropertyName("api_application_id")]
        public Guid? ApiApplicationId { get { return this.ApiApplicationIdOption.Value; } set { this.ApiApplicationIdOption = new Option<Guid?>(value); } }

        /// <summary>
        /// Used to track the state of RedirectUrl
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> RedirectUrlOption { get; private set; }

        /// <summary>
        /// A URL that recipients are redirected to after successfully signing a document.
        /// </summary>
        /// <value>A URL that recipients are redirected to after successfully signing a document.</value>
        [JsonPropertyName("redirect_url")]
        public string? RedirectUrl { get { return this.RedirectUrlOption.Value; } set { this.RedirectUrlOption = new Option<string?>(value); } }

        /// <summary>
        /// Used to track the state of AllowDecline
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> AllowDeclineOption { get; private set; }

        /// <summary>
        /// Whether to allow recipients the option to decline signing a document. If multiple signers are involved in a document, any single recipient can cancel the entire document signing process by declining to sign.
        /// </summary>
        /// <value>Whether to allow recipients the option to decline signing a document. If multiple signers are involved in a document, any single recipient can cancel the entire document signing process by declining to sign.</value>
        [JsonPropertyName("allow_decline")]
        public bool? AllowDecline { get { return this.AllowDeclineOption.Value; } set { this.AllowDeclineOption = new Option<bool?>(value); } }

        /// <summary>
        /// Used to track the state of AllowReassign
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> AllowReassignOption { get; private set; }

        /// <summary>
        /// In some cases a signer is not the right person to sign and may need to reassign their signing responsibilities to another person. This feature allows them to reassign the document to someone else.
        /// </summary>
        /// <value>In some cases a signer is not the right person to sign and may need to reassign their signing responsibilities to another person. This feature allows them to reassign the document to someone else.</value>
        [JsonPropertyName("allow_reassign")]
        public bool? AllowReassign { get { return this.AllowReassignOption.Value; } set { this.AllowReassignOption = new Option<bool?>(value); } }

        /// <summary>
        /// Used to track the state of DeclineRedirectUrl
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> DeclineRedirectUrlOption { get; private set; }

        /// <summary>
        /// A URL that recipients are redirected to if the document is declined.
        /// </summary>
        /// <value>A URL that recipients are redirected to if the document is declined.</value>
        [JsonPropertyName("decline_redirect_url")]
        public string? DeclineRedirectUrl { get { return this.DeclineRedirectUrlOption.Value; } set { this.DeclineRedirectUrlOption = new Option<string?>(value); } }

        /// <summary>
        /// Used to track the state of Metadata
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Dictionary<string, string>?> MetadataOption { get; private set; }

        /// <summary>
        /// Optional key-value data that can be associated with the document. If set, will be available every time the document data is returned.
        /// </summary>
        /// <value>Optional key-value data that can be associated with the document. If set, will be available every time the document data is returned.</value>
        [JsonPropertyName("metadata")]
        public Dictionary<string, string>? Metadata { get { return this.MetadataOption.Value; } set { this.MetadataOption = new Option<Dictionary<string, string>?>(value); } }

        /// <summary>
        /// Used to track the state of Labels
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<LabelRequest>?> LabelsOption { get; private set; }

        /// <summary>
        /// Labels can be used to organize documents in a way that can make it easy to find using the document search in SignWell. A document can have multiple labels. Updating labels on a document will replace any existing labels for that document.
        /// </summary>
        /// <value>Labels can be used to organize documents in a way that can make it easy to find using the document search in SignWell. A document can have multiple labels. Updating labels on a document will replace any existing labels for that document.</value>
        [JsonPropertyName("labels")]
        public List<LabelRequest>? Labels { get { return this.LabelsOption.Value; } set { this.LabelsOption = new Option<List<LabelRequest>?>(value); } }

        /// <summary>
        /// Used to track the state of CheckboxGroups
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<TemplateCheckboxGroupsInner>?> CheckboxGroupsOption { get; private set; }

        /// <summary>
        /// Checkbox fields that are placed on a document can be grouped with selection requirements. At least 2 checkbox fields in an array of fields must be assigned to the same recipient.
        /// </summary>
        /// <value>Checkbox fields that are placed on a document can be grouped with selection requirements. At least 2 checkbox fields in an array of fields must be assigned to the same recipient.</value>
        [JsonPropertyName("checkbox_groups")]
        public List<TemplateCheckboxGroupsInner>? CheckboxGroups { get { return this.CheckboxGroupsOption.Value; } set { this.CheckboxGroupsOption = new Option<List<TemplateCheckboxGroupsInner>?>(value); } }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DocumentTemplateUpdateRequest {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Subject: ").Append(Subject).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("  Draft: ").Append(Draft).Append("\n");
            sb.Append("  ExpiresIn: ").Append(ExpiresIn).Append("\n");
            sb.Append("  Reminders: ").Append(Reminders).Append("\n");
            sb.Append("  ApplySigningOrder: ").Append(ApplySigningOrder).Append("\n");
            sb.Append("  ApiApplicationId: ").Append(ApiApplicationId).Append("\n");
            sb.Append("  RedirectUrl: ").Append(RedirectUrl).Append("\n");
            sb.Append("  AllowDecline: ").Append(AllowDecline).Append("\n");
            sb.Append("  AllowReassign: ").Append(AllowReassign).Append("\n");
            sb.Append("  DeclineRedirectUrl: ").Append(DeclineRedirectUrl).Append("\n");
            sb.Append("  Metadata: ").Append(Metadata).Append("\n");
            sb.Append("  Labels: ").Append(Labels).Append("\n");
            sb.Append("  CheckboxGroups: ").Append(CheckboxGroups).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // ExpiresIn (int) minimum
            if (this.ExpiresInOption.IsSet && this.ExpiresInOption.Value < (int)1)
            {
                yield return new ValidationResult("Invalid value for ExpiresIn, must be a value greater than or equal to 1.", new [] { "ExpiresIn" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="DocumentTemplateUpdateRequest" />
    /// </summary>
    public class DocumentTemplateUpdateRequestJsonConverter : JsonConverter<DocumentTemplateUpdateRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="DocumentTemplateUpdateRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override DocumentTemplateUpdateRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> name = default;
            Option<string?> subject = default;
            Option<string?> message = default;
            Option<bool?> draft = default;
            Option<int?> expiresIn = default;
            Option<bool?> reminders = default;
            Option<bool?> applySigningOrder = default;
            Option<Guid?> apiApplicationId = default;
            Option<string?> redirectUrl = default;
            Option<bool?> allowDecline = default;
            Option<bool?> allowReassign = default;
            Option<string?> declineRedirectUrl = default;
            Option<Dictionary<string, string>?> metadata = default;
            Option<List<LabelRequest>?> labels = default;
            Option<List<TemplateCheckboxGroupsInner>?> checkboxGroups = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "subject":
                            subject = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "message":
                            message = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "draft":
                            draft = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "expires_in":
                            expiresIn = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "reminders":
                            reminders = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "apply_signing_order":
                            applySigningOrder = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "api_application_id":
                            apiApplicationId = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "redirect_url":
                            redirectUrl = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "allow_decline":
                            allowDecline = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "allow_reassign":
                            allowReassign = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "decline_redirect_url":
                            declineRedirectUrl = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "metadata":
                            metadata = new Option<Dictionary<string, string>?>(JsonSerializer.Deserialize<Dictionary<string, string>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "labels":
                            labels = new Option<List<LabelRequest>?>(JsonSerializer.Deserialize<List<LabelRequest>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "checkbox_groups":
                            checkboxGroups = new Option<List<TemplateCheckboxGroupsInner>?>(JsonSerializer.Deserialize<List<TemplateCheckboxGroupsInner>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class DocumentTemplateUpdateRequest.");

            if (subject.IsSet && subject.Value == null)
                throw new ArgumentNullException(nameof(subject), "Property is not nullable for class DocumentTemplateUpdateRequest.");

            if (message.IsSet && message.Value == null)
                throw new ArgumentNullException(nameof(message), "Property is not nullable for class DocumentTemplateUpdateRequest.");

            if (draft.IsSet && draft.Value == null)
                throw new ArgumentNullException(nameof(draft), "Property is not nullable for class DocumentTemplateUpdateRequest.");

            if (expiresIn.IsSet && expiresIn.Value == null)
                throw new ArgumentNullException(nameof(expiresIn), "Property is not nullable for class DocumentTemplateUpdateRequest.");

            if (reminders.IsSet && reminders.Value == null)
                throw new ArgumentNullException(nameof(reminders), "Property is not nullable for class DocumentTemplateUpdateRequest.");

            if (applySigningOrder.IsSet && applySigningOrder.Value == null)
                throw new ArgumentNullException(nameof(applySigningOrder), "Property is not nullable for class DocumentTemplateUpdateRequest.");

            if (apiApplicationId.IsSet && apiApplicationId.Value == null)
                throw new ArgumentNullException(nameof(apiApplicationId), "Property is not nullable for class DocumentTemplateUpdateRequest.");

            if (redirectUrl.IsSet && redirectUrl.Value == null)
                throw new ArgumentNullException(nameof(redirectUrl), "Property is not nullable for class DocumentTemplateUpdateRequest.");

            if (allowDecline.IsSet && allowDecline.Value == null)
                throw new ArgumentNullException(nameof(allowDecline), "Property is not nullable for class DocumentTemplateUpdateRequest.");

            if (allowReassign.IsSet && allowReassign.Value == null)
                throw new ArgumentNullException(nameof(allowReassign), "Property is not nullable for class DocumentTemplateUpdateRequest.");

            if (declineRedirectUrl.IsSet && declineRedirectUrl.Value == null)
                throw new ArgumentNullException(nameof(declineRedirectUrl), "Property is not nullable for class DocumentTemplateUpdateRequest.");

            if (metadata.IsSet && metadata.Value == null)
                throw new ArgumentNullException(nameof(metadata), "Property is not nullable for class DocumentTemplateUpdateRequest.");

            if (labels.IsSet && labels.Value == null)
                throw new ArgumentNullException(nameof(labels), "Property is not nullable for class DocumentTemplateUpdateRequest.");

            if (checkboxGroups.IsSet && checkboxGroups.Value == null)
                throw new ArgumentNullException(nameof(checkboxGroups), "Property is not nullable for class DocumentTemplateUpdateRequest.");

            return new DocumentTemplateUpdateRequest(name, subject, message, draft, expiresIn, reminders, applySigningOrder, apiApplicationId, redirectUrl, allowDecline, allowReassign, declineRedirectUrl, metadata, labels, checkboxGroups);
        }

        /// <summary>
        /// Serializes a <see cref="DocumentTemplateUpdateRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="documentTemplateUpdateRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, DocumentTemplateUpdateRequest documentTemplateUpdateRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, documentTemplateUpdateRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="DocumentTemplateUpdateRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="documentTemplateUpdateRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, DocumentTemplateUpdateRequest documentTemplateUpdateRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (documentTemplateUpdateRequest.NameOption.IsSet && documentTemplateUpdateRequest.Name == null)
                throw new ArgumentNullException(nameof(documentTemplateUpdateRequest.Name), "Property is required for class DocumentTemplateUpdateRequest.");

            if (documentTemplateUpdateRequest.SubjectOption.IsSet && documentTemplateUpdateRequest.Subject == null)
                throw new ArgumentNullException(nameof(documentTemplateUpdateRequest.Subject), "Property is required for class DocumentTemplateUpdateRequest.");

            if (documentTemplateUpdateRequest.MessageOption.IsSet && documentTemplateUpdateRequest.Message == null)
                throw new ArgumentNullException(nameof(documentTemplateUpdateRequest.Message), "Property is required for class DocumentTemplateUpdateRequest.");

            if (documentTemplateUpdateRequest.RedirectUrlOption.IsSet && documentTemplateUpdateRequest.RedirectUrl == null)
                throw new ArgumentNullException(nameof(documentTemplateUpdateRequest.RedirectUrl), "Property is required for class DocumentTemplateUpdateRequest.");

            if (documentTemplateUpdateRequest.DeclineRedirectUrlOption.IsSet && documentTemplateUpdateRequest.DeclineRedirectUrl == null)
                throw new ArgumentNullException(nameof(documentTemplateUpdateRequest.DeclineRedirectUrl), "Property is required for class DocumentTemplateUpdateRequest.");

            if (documentTemplateUpdateRequest.MetadataOption.IsSet && documentTemplateUpdateRequest.Metadata == null)
                throw new ArgumentNullException(nameof(documentTemplateUpdateRequest.Metadata), "Property is required for class DocumentTemplateUpdateRequest.");

            if (documentTemplateUpdateRequest.LabelsOption.IsSet && documentTemplateUpdateRequest.Labels == null)
                throw new ArgumentNullException(nameof(documentTemplateUpdateRequest.Labels), "Property is required for class DocumentTemplateUpdateRequest.");

            if (documentTemplateUpdateRequest.CheckboxGroupsOption.IsSet && documentTemplateUpdateRequest.CheckboxGroups == null)
                throw new ArgumentNullException(nameof(documentTemplateUpdateRequest.CheckboxGroups), "Property is required for class DocumentTemplateUpdateRequest.");

            if (documentTemplateUpdateRequest.NameOption.IsSet)
                writer.WriteString("name", documentTemplateUpdateRequest.Name);

            if (documentTemplateUpdateRequest.SubjectOption.IsSet)
                writer.WriteString("subject", documentTemplateUpdateRequest.Subject);

            if (documentTemplateUpdateRequest.MessageOption.IsSet)
                writer.WriteString("message", documentTemplateUpdateRequest.Message);

            if (documentTemplateUpdateRequest.DraftOption.IsSet)
                writer.WriteBoolean("draft", documentTemplateUpdateRequest.DraftOption.Value!.Value);

            if (documentTemplateUpdateRequest.ExpiresInOption.IsSet)
                writer.WriteNumber("expires_in", documentTemplateUpdateRequest.ExpiresInOption.Value!.Value);

            if (documentTemplateUpdateRequest.RemindersOption.IsSet)
                writer.WriteBoolean("reminders", documentTemplateUpdateRequest.RemindersOption.Value!.Value);

            if (documentTemplateUpdateRequest.ApplySigningOrderOption.IsSet)
                writer.WriteBoolean("apply_signing_order", documentTemplateUpdateRequest.ApplySigningOrderOption.Value!.Value);

            if (documentTemplateUpdateRequest.ApiApplicationIdOption.IsSet)
                writer.WriteString("api_application_id", documentTemplateUpdateRequest.ApiApplicationIdOption.Value!.Value);

            if (documentTemplateUpdateRequest.RedirectUrlOption.IsSet)
                writer.WriteString("redirect_url", documentTemplateUpdateRequest.RedirectUrl);

            if (documentTemplateUpdateRequest.AllowDeclineOption.IsSet)
                writer.WriteBoolean("allow_decline", documentTemplateUpdateRequest.AllowDeclineOption.Value!.Value);

            if (documentTemplateUpdateRequest.AllowReassignOption.IsSet)
                writer.WriteBoolean("allow_reassign", documentTemplateUpdateRequest.AllowReassignOption.Value!.Value);

            if (documentTemplateUpdateRequest.DeclineRedirectUrlOption.IsSet)
                writer.WriteString("decline_redirect_url", documentTemplateUpdateRequest.DeclineRedirectUrl);

            if (documentTemplateUpdateRequest.MetadataOption.IsSet)
            {
                writer.WritePropertyName("metadata");
                JsonSerializer.Serialize(writer, documentTemplateUpdateRequest.Metadata, jsonSerializerOptions);
            }
            if (documentTemplateUpdateRequest.LabelsOption.IsSet)
            {
                writer.WritePropertyName("labels");
                JsonSerializer.Serialize(writer, documentTemplateUpdateRequest.Labels, jsonSerializerOptions);
            }
            if (documentTemplateUpdateRequest.CheckboxGroupsOption.IsSet)
            {
                writer.WritePropertyName("checkbox_groups");
                JsonSerializer.Serialize(writer, documentTemplateUpdateRequest.CheckboxGroups, jsonSerializerOptions);
            }
        }
    }
}
