// <auto-generated>
/*
 * SignWell Developer API
 *
 * API for creating, managing, and tracking electronic signature workflows.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@signwell.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using SignWell.Sdk.Client;

namespace SignWell.Sdk.Models
{
    /// <summary>
    /// Format of the file to be downloaded. Supported formats are &#39;pdf&#39; and &#39;zip&#39;.
    /// </summary>
    /// <value>Format of the file to be downloaded. Supported formats are &#39;pdf&#39; and &#39;zip&#39;.</value>
    public enum FileFormat
    {
        /// <summary>
        /// Enum Pdf for value: pdf
        /// </summary>
        Pdf = 1,

        /// <summary>
        /// Enum Zip for value: zip
        /// </summary>
        Zip = 2,

        /// <summary>
        /// Enum UnknownDefaultOpenApi for value: unknown_default_open_api
        /// </summary>
        UnknownDefaultOpenApi = 3
    }

    /// <summary>
    /// Converts <see cref="FileFormat"/> to and from the JSON value
    /// </summary>
    public static class FileFormatValueConverter
    {
        /// <summary>
        /// Parses a given value to <see cref="FileFormat"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static FileFormat FromString(string value)
        {
            if (value.Equals("pdf"))
                return FileFormat.Pdf;

            if (value.Equals("zip"))
                return FileFormat.Zip;

            if (value.Equals("unknown_default_open_api"))
                return FileFormat.UnknownDefaultOpenApi;

            throw new NotImplementedException($"Could not convert value to type FileFormat: '{value}'");
        }

        /// <summary>
        /// Parses a given value to <see cref="FileFormat"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static FileFormat? FromStringOrDefault(string value)
        {
            if (value.Equals("pdf"))
                return FileFormat.Pdf;

            if (value.Equals("zip"))
                return FileFormat.Zip;

            if (value.Equals("unknown_default_open_api"))
                return FileFormat.UnknownDefaultOpenApi;

            return FileFormat.UnknownDefaultOpenApi;
        }

        /// <summary>
        /// Converts the <see cref="FileFormat"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ToJsonValue(FileFormat value)
        {
            if (value == FileFormat.Pdf)
                return "pdf";

            if (value == FileFormat.Zip)
                return "zip";

            if (value == FileFormat.UnknownDefaultOpenApi)
                return "unknown_default_open_api";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="FileFormat"/>
    /// </summary>
    /// <exception cref="NotImplementedException"></exception>
    public class FileFormatJsonConverter : JsonConverter<FileFormat>
    {
        /// <summary>
        /// Returns a  from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override FileFormat Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            FileFormat? result = rawValue == null
                ? null
                : FileFormatValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the FileFormat to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="fileFormat"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, FileFormat fileFormat, JsonSerializerOptions options)
        {
            writer.WriteStringValue(FileFormatValueConverter.ToJsonValue(fileFormat).ToString());
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="FileFormat"/>
    /// </summary>
    public class FileFormatNullableJsonConverter : JsonConverter<FileFormat?>
    {
        /// <summary>
        /// Returns a FileFormat from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override FileFormat? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            FileFormat? result = rawValue == null
                ? null
                : FileFormatValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the FileFormat to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="fileFormat"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, FileFormat? fileFormat, JsonSerializerOptions options)
        {
            writer.WriteStringValue(fileFormat.HasValue ? FileFormatValueConverter.ToJsonValue(fileFormat.Value).ToString() : "null");
        }
    }
}
