// <auto-generated>
/*
 * SignWell Developer API
 *
 * API for creating, managing, and tracking electronic signature workflows.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@signwell.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using SignWell.Sdk.Client;

namespace SignWell.Sdk.Models
{
    /// <summary>
    /// MeResponseUserPreferences
    /// </summary>
    public partial class MeResponseUserPreferences : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MeResponseUserPreferences" /> class.
        /// </summary>
        /// <param name="salesDocument">salesDocument</param>
        /// <param name="varTimeZone">varTimeZone</param>
        /// <param name="smartFields">smartFields</param>
        [JsonConstructor]
        public MeResponseUserPreferences(Option<bool?> salesDocument = default, Option<string?> varTimeZone = default, Option<bool?> smartFields = default)
        {
            SalesDocumentOption = salesDocument;
            VarTimeZoneOption = varTimeZone;
            SmartFieldsOption = smartFields;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of SalesDocument
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> SalesDocumentOption { get; private set; }

        /// <summary>
        /// Gets or Sets SalesDocument
        /// </summary>
        [JsonPropertyName("sales_document")]
        public bool? SalesDocument { get { return this.SalesDocumentOption.Value; } set { this.SalesDocumentOption = new Option<bool?>(value); } }

        /// <summary>
        /// Used to track the state of VarTimeZone
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> VarTimeZoneOption { get; private set; }

        /// <summary>
        /// Gets or Sets VarTimeZone
        /// </summary>
        [JsonPropertyName("time_zone")]
        public string? VarTimeZone { get { return this.VarTimeZoneOption.Value; } set { this.VarTimeZoneOption = new Option<string?>(value); } }

        /// <summary>
        /// Used to track the state of SmartFields
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> SmartFieldsOption { get; private set; }

        /// <summary>
        /// Gets or Sets SmartFields
        /// </summary>
        [JsonPropertyName("smart_fields")]
        public bool? SmartFields { get { return this.SmartFieldsOption.Value; } set { this.SmartFieldsOption = new Option<bool?>(value); } }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MeResponseUserPreferences {\n");
            sb.Append("  SalesDocument: ").Append(SalesDocument).Append("\n");
            sb.Append("  VarTimeZone: ").Append(VarTimeZone).Append("\n");
            sb.Append("  SmartFields: ").Append(SmartFields).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="MeResponseUserPreferences" />
    /// </summary>
    public class MeResponseUserPreferencesJsonConverter : JsonConverter<MeResponseUserPreferences>
    {
        /// <summary>
        /// Deserializes json to <see cref="MeResponseUserPreferences" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override MeResponseUserPreferences Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<bool?> salesDocument = default;
            Option<string?> varTimeZone = default;
            Option<bool?> smartFields = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "sales_document":
                            salesDocument = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "time_zone":
                            varTimeZone = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "smart_fields":
                            smartFields = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (salesDocument.IsSet && salesDocument.Value == null)
                throw new ArgumentNullException(nameof(salesDocument), "Property is not nullable for class MeResponseUserPreferences.");

            if (varTimeZone.IsSet && varTimeZone.Value == null)
                throw new ArgumentNullException(nameof(varTimeZone), "Property is not nullable for class MeResponseUserPreferences.");

            if (smartFields.IsSet && smartFields.Value == null)
                throw new ArgumentNullException(nameof(smartFields), "Property is not nullable for class MeResponseUserPreferences.");

            return new MeResponseUserPreferences(salesDocument, varTimeZone, smartFields);
        }

        /// <summary>
        /// Serializes a <see cref="MeResponseUserPreferences" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="meResponseUserPreferences"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, MeResponseUserPreferences meResponseUserPreferences, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, meResponseUserPreferences, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="MeResponseUserPreferences" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="meResponseUserPreferences"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, MeResponseUserPreferences meResponseUserPreferences, JsonSerializerOptions jsonSerializerOptions)
        {
            if (meResponseUserPreferences.VarTimeZoneOption.IsSet && meResponseUserPreferences.VarTimeZone == null)
                throw new ArgumentNullException(nameof(meResponseUserPreferences.VarTimeZone), "Property is required for class MeResponseUserPreferences.");

            if (meResponseUserPreferences.SalesDocumentOption.IsSet)
                writer.WriteBoolean("sales_document", meResponseUserPreferences.SalesDocumentOption.Value!.Value);

            if (meResponseUserPreferences.VarTimeZoneOption.IsSet)
                writer.WriteString("time_zone", meResponseUserPreferences.VarTimeZone);

            if (meResponseUserPreferences.SmartFieldsOption.IsSet)
                writer.WriteBoolean("smart_fields", meResponseUserPreferences.SmartFieldsOption.Value!.Value);
        }
    }
}
