// <auto-generated>
/*
 * SignWell Developer API
 *
 * API for creating, managing, and tracking electronic signature workflows.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@signwell.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using SignWell.Sdk.Client;

namespace SignWell.Sdk.Models
{
    /// <summary>
    /// Pagination metadata for list responses
    /// </summary>
    public partial class PaginationMeta : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PaginationMeta" /> class.
        /// </summary>
        /// <param name="currentPage">Current page number</param>
        /// <param name="totalCount">Total number of records</param>
        /// <param name="totalPages">Total number of pages</param>
        /// <param name="nextPage">Next page number, null if on last page</param>
        /// <param name="previousPage">Previous page number, null if on first page</param>
        [JsonConstructor]
        public PaginationMeta(int currentPage, int totalCount, int totalPages, Option<int?> nextPage = default, Option<int?> previousPage = default)
        {
            CurrentPage = currentPage;
            TotalCount = totalCount;
            TotalPages = totalPages;
            NextPageOption = nextPage;
            PreviousPageOption = previousPage;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Current page number
        /// </summary>
        /// <value>Current page number</value>
        [JsonPropertyName("current_page")]
        public int CurrentPage { get; set; }

        /// <summary>
        /// Total number of records
        /// </summary>
        /// <value>Total number of records</value>
        [JsonPropertyName("total_count")]
        public int TotalCount { get; set; }

        /// <summary>
        /// Total number of pages
        /// </summary>
        /// <value>Total number of pages</value>
        [JsonPropertyName("total_pages")]
        public int TotalPages { get; set; }

        /// <summary>
        /// Used to track the state of NextPage
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> NextPageOption { get; private set; }

        /// <summary>
        /// Next page number, null if on last page
        /// </summary>
        /// <value>Next page number, null if on last page</value>
        [JsonPropertyName("next_page")]
        public int? NextPage { get { return this.NextPageOption.Value; } set { this.NextPageOption = new Option<int?>(value); } }

        /// <summary>
        /// Used to track the state of PreviousPage
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> PreviousPageOption { get; private set; }

        /// <summary>
        /// Previous page number, null if on first page
        /// </summary>
        /// <value>Previous page number, null if on first page</value>
        [JsonPropertyName("previous_page")]
        public int? PreviousPage { get { return this.PreviousPageOption.Value; } set { this.PreviousPageOption = new Option<int?>(value); } }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PaginationMeta {\n");
            sb.Append("  CurrentPage: ").Append(CurrentPage).Append("\n");
            sb.Append("  TotalCount: ").Append(TotalCount).Append("\n");
            sb.Append("  TotalPages: ").Append(TotalPages).Append("\n");
            sb.Append("  NextPage: ").Append(NextPage).Append("\n");
            sb.Append("  PreviousPage: ").Append(PreviousPage).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="PaginationMeta" />
    /// </summary>
    public class PaginationMetaJsonConverter : JsonConverter<PaginationMeta>
    {
        /// <summary>
        /// Deserializes json to <see cref="PaginationMeta" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override PaginationMeta Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> currentPage = default;
            Option<int?> totalCount = default;
            Option<int?> totalPages = default;
            Option<int?> nextPage = default;
            Option<int?> previousPage = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "current_page":
                            currentPage = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "total_count":
                            totalCount = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "total_pages":
                            totalPages = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "next_page":
                            nextPage = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "previous_page":
                            previousPage = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!currentPage.IsSet)
                throw new ArgumentException("Property is required for class PaginationMeta.", nameof(currentPage));

            if (!totalCount.IsSet)
                throw new ArgumentException("Property is required for class PaginationMeta.", nameof(totalCount));

            if (!totalPages.IsSet)
                throw new ArgumentException("Property is required for class PaginationMeta.", nameof(totalPages));

            if (currentPage.IsSet && currentPage.Value == null)
                throw new ArgumentNullException(nameof(currentPage), "Property is not nullable for class PaginationMeta.");

            if (totalCount.IsSet && totalCount.Value == null)
                throw new ArgumentNullException(nameof(totalCount), "Property is not nullable for class PaginationMeta.");

            if (totalPages.IsSet && totalPages.Value == null)
                throw new ArgumentNullException(nameof(totalPages), "Property is not nullable for class PaginationMeta.");

            return new PaginationMeta(currentPage.Value!.Value!, totalCount.Value!.Value!, totalPages.Value!.Value!, nextPage, previousPage);
        }

        /// <summary>
        /// Serializes a <see cref="PaginationMeta" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="paginationMeta"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, PaginationMeta paginationMeta, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, paginationMeta, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="PaginationMeta" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="paginationMeta"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, PaginationMeta paginationMeta, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteNumber("current_page", paginationMeta.CurrentPage);

            writer.WriteNumber("total_count", paginationMeta.TotalCount);

            writer.WriteNumber("total_pages", paginationMeta.TotalPages);

            if (paginationMeta.NextPageOption.IsSet)
                if (paginationMeta.NextPageOption.Value != null)
                    writer.WriteNumber("next_page", paginationMeta.NextPageOption.Value!.Value);
                else
                    writer.WriteNull("next_page");

            if (paginationMeta.PreviousPageOption.IsSet)
                if (paginationMeta.PreviousPageOption.Value != null)
                    writer.WriteNumber("previous_page", paginationMeta.PreviousPageOption.Value!.Value);
                else
                    writer.WriteNull("previous_page");
        }
    }
}
