// <auto-generated>
/*
 * SignWell Developer API
 *
 * API for creating, managing, and tracking electronic signature workflows.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@signwell.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using SignWell.Sdk.Client;

namespace SignWell.Sdk.Models
{
    /// <summary>
    /// Rate limit exceeded error response (HTTP 429)
    /// </summary>
    public partial class RateLimitErrorResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RateLimitErrorResponse" /> class.
        /// </summary>
        /// <param name="error">Rate limit error message indicating the limit and reset time</param>
        [JsonConstructor]
        public RateLimitErrorResponse(string error)
        {
            Error = error;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Rate limit error message indicating the limit and reset time
        /// </summary>
        /// <value>Rate limit error message indicating the limit and reset time</value>
        [JsonPropertyName("error")]
        public string Error { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RateLimitErrorResponse {\n");
            sb.Append("  Error: ").Append(Error).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="RateLimitErrorResponse" />
    /// </summary>
    public class RateLimitErrorResponseJsonConverter : JsonConverter<RateLimitErrorResponse>
    {
        /// <summary>
        /// Deserializes json to <see cref="RateLimitErrorResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override RateLimitErrorResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> error = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "error":
                            error = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!error.IsSet)
                throw new ArgumentException("Property is required for class RateLimitErrorResponse.", nameof(error));

            if (error.IsSet && error.Value == null)
                throw new ArgumentNullException(nameof(error), "Property is not nullable for class RateLimitErrorResponse.");

            return new RateLimitErrorResponse(error.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="RateLimitErrorResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="rateLimitErrorResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, RateLimitErrorResponse rateLimitErrorResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, rateLimitErrorResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="RateLimitErrorResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="rateLimitErrorResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, RateLimitErrorResponse rateLimitErrorResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (rateLimitErrorResponse.Error == null)
                throw new ArgumentNullException(nameof(rateLimitErrorResponse.Error), "Property is required for class RateLimitErrorResponse.");

            writer.WriteString("error", rateLimitErrorResponse.Error);
        }
    }
}
