// <auto-generated>
/*
 * SignWell Developer API
 *
 * API for creating, managing, and tracking electronic signature workflows.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@signwell.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using SignWell.Sdk.Client;

namespace SignWell.Sdk.Models
{
    /// <summary>
    /// TemplateRecipientsInner
    /// </summary>
    public partial class TemplateRecipientsInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TemplateRecipientsInner" /> class.
        /// </summary>
        /// <param name="id">A unique identifier that you will give to each recipient. We recommend numbering sequentially from 1 to X. IDs are required for associating recipients to fields and more.</param>
        /// <param name="email">Email address for the recipient.</param>
        /// <param name="name">Name of the recipient.</param>
        /// <param name="placeholderName">The name of the placeholder you want this recipient assigned to.</param>
        /// <param name="passcode">If set, signers assigned with a passcode will be required to enter the passcode before they’re able to view and complete the document.</param>
        /// <param name="subject">Email subject for the signature request that the recipient will see. Overrides the general subject for the template.</param>
        /// <param name="message">Email message for the signature request that the recipient will see. Overrides the general message for the template.</param>
        /// <param name="sendEmail">Applies on when &#x60;embedded_signing&#x60; is &#x60;true&#x60;. By default, recipients are not notified through email to sign when doing embedded signing. Setting this to &#x60;true&#x60;  will send a notification email to the recipient. Default is &#x60;false&#x60;. (default to false)</param>
        /// <param name="sendEmailDelay">If &#x60;send_email&#x60; is &#x60;true&#x60; recipients will receive a new document notification immediately. In the case of embedded signing, you can delay this notification to only send if the document is not completed within a few minutes. The email notification will not go out if the document is completed before the delay time is over. Valid values are in minutes ranging from &#x60;0&#x60; to &#x60;60&#x60;. Defaults to &#x60;0&#x60;. (default to 0)</param>
        [JsonConstructor]
        public TemplateRecipientsInner(string id, string email, Option<string?> name = default, Option<string?> placeholderName = default, Option<string?> passcode = default, Option<string?> subject = default, Option<string?> message = default, Option<bool?> sendEmail = default, Option<int?> sendEmailDelay = default)
        {
            Id = id;
            Email = email;
            NameOption = name;
            PlaceholderNameOption = placeholderName;
            PasscodeOption = passcode;
            SubjectOption = subject;
            MessageOption = message;
            SendEmailOption = sendEmail;
            SendEmailDelayOption = sendEmailDelay;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// A unique identifier that you will give to each recipient. We recommend numbering sequentially from 1 to X. IDs are required for associating recipients to fields and more.
        /// </summary>
        /// <value>A unique identifier that you will give to each recipient. We recommend numbering sequentially from 1 to X. IDs are required for associating recipients to fields and more.</value>
        [JsonPropertyName("id")]
        public string Id { get; set; }

        /// <summary>
        /// Email address for the recipient.
        /// </summary>
        /// <value>Email address for the recipient.</value>
        /* <example>signer@example.com</example> */
        [JsonPropertyName("email")]
        public string Email { get; set; }

        /// <summary>
        /// Used to track the state of Name
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NameOption { get; private set; }

        /// <summary>
        /// Name of the recipient.
        /// </summary>
        /// <value>Name of the recipient.</value>
        [JsonPropertyName("name")]
        public string? Name { get { return this.NameOption.Value; } set { this.NameOption = new Option<string?>(value); } }

        /// <summary>
        /// Used to track the state of PlaceholderName
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> PlaceholderNameOption { get; private set; }

        /// <summary>
        /// The name of the placeholder you want this recipient assigned to.
        /// </summary>
        /// <value>The name of the placeholder you want this recipient assigned to.</value>
        [JsonPropertyName("placeholder_name")]
        public string? PlaceholderName { get { return this.PlaceholderNameOption.Value; } set { this.PlaceholderNameOption = new Option<string?>(value); } }

        /// <summary>
        /// Used to track the state of Passcode
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> PasscodeOption { get; private set; }

        /// <summary>
        /// If set, signers assigned with a passcode will be required to enter the passcode before they’re able to view and complete the document.
        /// </summary>
        /// <value>If set, signers assigned with a passcode will be required to enter the passcode before they’re able to view and complete the document.</value>
        [JsonPropertyName("passcode")]
        public string? Passcode { get { return this.PasscodeOption.Value; } set { this.PasscodeOption = new Option<string?>(value); } }

        /// <summary>
        /// Used to track the state of Subject
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> SubjectOption { get; private set; }

        /// <summary>
        /// Email subject for the signature request that the recipient will see. Overrides the general subject for the template.
        /// </summary>
        /// <value>Email subject for the signature request that the recipient will see. Overrides the general subject for the template.</value>
        [JsonPropertyName("subject")]
        public string? Subject { get { return this.SubjectOption.Value; } set { this.SubjectOption = new Option<string?>(value); } }

        /// <summary>
        /// Used to track the state of Message
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> MessageOption { get; private set; }

        /// <summary>
        /// Email message for the signature request that the recipient will see. Overrides the general message for the template.
        /// </summary>
        /// <value>Email message for the signature request that the recipient will see. Overrides the general message for the template.</value>
        [JsonPropertyName("message")]
        public string? Message { get { return this.MessageOption.Value; } set { this.MessageOption = new Option<string?>(value); } }

        /// <summary>
        /// Used to track the state of SendEmail
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> SendEmailOption { get; private set; }

        /// <summary>
        /// Applies on when &#x60;embedded_signing&#x60; is &#x60;true&#x60;. By default, recipients are not notified through email to sign when doing embedded signing. Setting this to &#x60;true&#x60;  will send a notification email to the recipient. Default is &#x60;false&#x60;.
        /// </summary>
        /// <value>Applies on when &#x60;embedded_signing&#x60; is &#x60;true&#x60;. By default, recipients are not notified through email to sign when doing embedded signing. Setting this to &#x60;true&#x60;  will send a notification email to the recipient. Default is &#x60;false&#x60;.</value>
        [JsonPropertyName("send_email")]
        public bool? SendEmail { get { return this.SendEmailOption.Value; } set { this.SendEmailOption = new Option<bool?>(value); } }

        /// <summary>
        /// Used to track the state of SendEmailDelay
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> SendEmailDelayOption { get; private set; }

        /// <summary>
        /// If &#x60;send_email&#x60; is &#x60;true&#x60; recipients will receive a new document notification immediately. In the case of embedded signing, you can delay this notification to only send if the document is not completed within a few minutes. The email notification will not go out if the document is completed before the delay time is over. Valid values are in minutes ranging from &#x60;0&#x60; to &#x60;60&#x60;. Defaults to &#x60;0&#x60;.
        /// </summary>
        /// <value>If &#x60;send_email&#x60; is &#x60;true&#x60; recipients will receive a new document notification immediately. In the case of embedded signing, you can delay this notification to only send if the document is not completed within a few minutes. The email notification will not go out if the document is completed before the delay time is over. Valid values are in minutes ranging from &#x60;0&#x60; to &#x60;60&#x60;. Defaults to &#x60;0&#x60;.</value>
        [JsonPropertyName("send_email_delay")]
        public int? SendEmailDelay { get { return this.SendEmailDelayOption.Value; } set { this.SendEmailDelayOption = new Option<int?>(value); } }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TemplateRecipientsInner {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  PlaceholderName: ").Append(PlaceholderName).Append("\n");
            sb.Append("  Passcode: ").Append(Passcode).Append("\n");
            sb.Append("  Subject: ").Append(Subject).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("  SendEmail: ").Append(SendEmail).Append("\n");
            sb.Append("  SendEmailDelay: ").Append(SendEmailDelay).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="TemplateRecipientsInner" />
    /// </summary>
    public class TemplateRecipientsInnerJsonConverter : JsonConverter<TemplateRecipientsInner>
    {
        /// <summary>
        /// Deserializes json to <see cref="TemplateRecipientsInner" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override TemplateRecipientsInner Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> id = default;
            Option<string?> email = default;
            Option<string?> name = default;
            Option<string?> placeholderName = default;
            Option<string?> passcode = default;
            Option<string?> subject = default;
            Option<string?> message = default;
            Option<bool?> sendEmail = default;
            Option<int?> sendEmailDelay = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "email":
                            email = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "placeholder_name":
                            placeholderName = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "passcode":
                            passcode = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "subject":
                            subject = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "message":
                            message = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "send_email":
                            sendEmail = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "send_email_delay":
                            sendEmailDelay = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!id.IsSet)
                throw new ArgumentException("Property is required for class TemplateRecipientsInner.", nameof(id));

            if (!email.IsSet)
                throw new ArgumentException("Property is required for class TemplateRecipientsInner.", nameof(email));

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class TemplateRecipientsInner.");

            if (email.IsSet && email.Value == null)
                throw new ArgumentNullException(nameof(email), "Property is not nullable for class TemplateRecipientsInner.");

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class TemplateRecipientsInner.");

            if (placeholderName.IsSet && placeholderName.Value == null)
                throw new ArgumentNullException(nameof(placeholderName), "Property is not nullable for class TemplateRecipientsInner.");

            if (passcode.IsSet && passcode.Value == null)
                throw new ArgumentNullException(nameof(passcode), "Property is not nullable for class TemplateRecipientsInner.");

            if (subject.IsSet && subject.Value == null)
                throw new ArgumentNullException(nameof(subject), "Property is not nullable for class TemplateRecipientsInner.");

            if (message.IsSet && message.Value == null)
                throw new ArgumentNullException(nameof(message), "Property is not nullable for class TemplateRecipientsInner.");

            if (sendEmail.IsSet && sendEmail.Value == null)
                throw new ArgumentNullException(nameof(sendEmail), "Property is not nullable for class TemplateRecipientsInner.");

            if (sendEmailDelay.IsSet && sendEmailDelay.Value == null)
                throw new ArgumentNullException(nameof(sendEmailDelay), "Property is not nullable for class TemplateRecipientsInner.");

            return new TemplateRecipientsInner(id.Value!, email.Value!, name, placeholderName, passcode, subject, message, sendEmail, sendEmailDelay);
        }

        /// <summary>
        /// Serializes a <see cref="TemplateRecipientsInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="templateRecipientsInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, TemplateRecipientsInner templateRecipientsInner, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, templateRecipientsInner, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="TemplateRecipientsInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="templateRecipientsInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, TemplateRecipientsInner templateRecipientsInner, JsonSerializerOptions jsonSerializerOptions)
        {
            if (templateRecipientsInner.Id == null)
                throw new ArgumentNullException(nameof(templateRecipientsInner.Id), "Property is required for class TemplateRecipientsInner.");

            if (templateRecipientsInner.Email == null)
                throw new ArgumentNullException(nameof(templateRecipientsInner.Email), "Property is required for class TemplateRecipientsInner.");

            if (templateRecipientsInner.NameOption.IsSet && templateRecipientsInner.Name == null)
                throw new ArgumentNullException(nameof(templateRecipientsInner.Name), "Property is required for class TemplateRecipientsInner.");

            if (templateRecipientsInner.PlaceholderNameOption.IsSet && templateRecipientsInner.PlaceholderName == null)
                throw new ArgumentNullException(nameof(templateRecipientsInner.PlaceholderName), "Property is required for class TemplateRecipientsInner.");

            if (templateRecipientsInner.PasscodeOption.IsSet && templateRecipientsInner.Passcode == null)
                throw new ArgumentNullException(nameof(templateRecipientsInner.Passcode), "Property is required for class TemplateRecipientsInner.");

            if (templateRecipientsInner.SubjectOption.IsSet && templateRecipientsInner.Subject == null)
                throw new ArgumentNullException(nameof(templateRecipientsInner.Subject), "Property is required for class TemplateRecipientsInner.");

            if (templateRecipientsInner.MessageOption.IsSet && templateRecipientsInner.Message == null)
                throw new ArgumentNullException(nameof(templateRecipientsInner.Message), "Property is required for class TemplateRecipientsInner.");

            writer.WriteString("id", templateRecipientsInner.Id);

            writer.WriteString("email", templateRecipientsInner.Email);

            if (templateRecipientsInner.NameOption.IsSet)
                writer.WriteString("name", templateRecipientsInner.Name);

            if (templateRecipientsInner.PlaceholderNameOption.IsSet)
                writer.WriteString("placeholder_name", templateRecipientsInner.PlaceholderName);

            if (templateRecipientsInner.PasscodeOption.IsSet)
                writer.WriteString("passcode", templateRecipientsInner.Passcode);

            if (templateRecipientsInner.SubjectOption.IsSet)
                writer.WriteString("subject", templateRecipientsInner.Subject);

            if (templateRecipientsInner.MessageOption.IsSet)
                writer.WriteString("message", templateRecipientsInner.Message);

            if (templateRecipientsInner.SendEmailOption.IsSet)
                writer.WriteBoolean("send_email", templateRecipientsInner.SendEmailOption.Value!.Value);

            if (templateRecipientsInner.SendEmailDelayOption.IsSet)
                writer.WriteNumber("send_email_delay", templateRecipientsInner.SendEmailDelayOption.Value!.Value);
        }
    }
}
