// <auto-generated>
/*
 * SignWell Developer API
 *
 * API for creating, managing, and tracking electronic signature workflows.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@signwell.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using SignWell.Sdk.Client;

namespace SignWell.Sdk.Models
{
    /// <summary>
    /// UpdateRecipientsRequest
    /// </summary>
    public partial class UpdateRecipientsRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateRecipientsRequest" /> class.
        /// </summary>
        /// <param name="recipients">List of recipients to update on the document.</param>
        [JsonConstructor]
        public UpdateRecipientsRequest(List<UpdateRecipientsMapInner> recipients)
        {
            Recipients = recipients;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// List of recipients to update on the document.
        /// </summary>
        /// <value>List of recipients to update on the document.</value>
        [JsonPropertyName("recipients")]
        public List<UpdateRecipientsMapInner> Recipients { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UpdateRecipientsRequest {\n");
            sb.Append("  Recipients: ").Append(Recipients).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="UpdateRecipientsRequest" />
    /// </summary>
    public class UpdateRecipientsRequestJsonConverter : JsonConverter<UpdateRecipientsRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="UpdateRecipientsRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override UpdateRecipientsRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<List<UpdateRecipientsMapInner>?> recipients = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "recipients":
                            recipients = new Option<List<UpdateRecipientsMapInner>?>(JsonSerializer.Deserialize<List<UpdateRecipientsMapInner>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!recipients.IsSet)
                throw new ArgumentException("Property is required for class UpdateRecipientsRequest.", nameof(recipients));

            if (recipients.IsSet && recipients.Value == null)
                throw new ArgumentNullException(nameof(recipients), "Property is not nullable for class UpdateRecipientsRequest.");

            return new UpdateRecipientsRequest(recipients.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="UpdateRecipientsRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="updateRecipientsRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, UpdateRecipientsRequest updateRecipientsRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, updateRecipientsRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="UpdateRecipientsRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="updateRecipientsRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, UpdateRecipientsRequest updateRecipientsRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (updateRecipientsRequest.Recipients == null)
                throw new ArgumentNullException(nameof(updateRecipientsRequest.Recipients), "Property is required for class UpdateRecipientsRequest.");

            writer.WritePropertyName("recipients");
            JsonSerializer.Serialize(writer, updateRecipientsRequest.Recipients, jsonSerializerOptions);
        }
    }
}
