/*
 * SignWell Developer API
 *
 * API for creating, managing, and tracking electronic signature workflows.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@signwell.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.DependencyInjection;
using System.Collections.Generic;
using System.Security.Cryptography;
using SignWell.Sdk.Client;
using SignWell.Sdk.Raw;
using SignWell.Sdk.Extensions;
using Xunit;

namespace SignWell.Sdk.Test.Raw
{
    /// <summary>
    ///  Tests the dependency injection.
    /// </summary>
    public class DependencyInjectionTest
    {
        private readonly IHost _hostUsingConfigureWithoutAClient =
            Host.CreateDefaultBuilder(Array.Empty<string>()).ConfigureApi((context, services, options) =>
            {
                ApiKeyToken apiKeyToken1 = new ApiKeyToken("<token>", ClientUtils.ApiKeyHeader.X_Api_Key, timeout: TimeSpan.FromSeconds(1));
                options.AddTokens(apiKeyToken1);
            })
            .Build();

        private readonly IHost _hostUsingConfigureWithAClient =
            Host.CreateDefaultBuilder(Array.Empty<string>()).ConfigureApi((context, services, options) =>
            {
                ApiKeyToken apiKeyToken1 = new ApiKeyToken("<token>", ClientUtils.ApiKeyHeader.X_Api_Key, timeout: TimeSpan.FromSeconds(1));
                options.AddTokens(apiKeyToken1);
                options.AddApiHttpClients(client => client.BaseAddress = new Uri(ClientUtils.BASE_ADDRESS));
            })
            .Build();

        private readonly IHost _hostUsingAddWithoutAClient =
            Host.CreateDefaultBuilder(Array.Empty<string>()).ConfigureServices((host, services) =>
            {
                services.AddApi(options =>
                {
                    ApiKeyToken apiKeyToken1 = new ApiKeyToken("<token>", ClientUtils.ApiKeyHeader.X_Api_Key, timeout: TimeSpan.FromSeconds(1));
                    options.AddTokens(apiKeyToken1);
                });
            })
            .Build();

        private readonly IHost _hostUsingAddWithAClient =
            Host.CreateDefaultBuilder(Array.Empty<string>()).ConfigureServices((host, services) =>
            {
                services.AddApi(options =>
                {
                    ApiKeyToken apiKeyToken1 = new ApiKeyToken("<token>", ClientUtils.ApiKeyHeader.X_Api_Key, timeout: TimeSpan.FromSeconds(1));
                    options.AddTokens(apiKeyToken1);
                    options.AddApiHttpClients(client => client.BaseAddress = new Uri(ClientUtils.BASE_ADDRESS));
                });
            })
            .Build();

        /// <summary>
        /// Test dependency injection when using the configure method
        /// </summary>
        [Fact]
        public void ConfigureApiWithAClientTest()
        {
            var apiApplicationApi = _hostUsingConfigureWithAClient.Services.GetRequiredService<IApiApplicationApi>();
            Assert.True(apiApplicationApi.HttpClient.BaseAddress != null);

            var bulkSendApi = _hostUsingConfigureWithAClient.Services.GetRequiredService<IBulkSendApi>();
            Assert.True(bulkSendApi.HttpClient.BaseAddress != null);

            var documentApi = _hostUsingConfigureWithAClient.Services.GetRequiredService<IDocumentApi>();
            Assert.True(documentApi.HttpClient.BaseAddress != null);

            var meApi = _hostUsingConfigureWithAClient.Services.GetRequiredService<IMeApi>();
            Assert.True(meApi.HttpClient.BaseAddress != null);

            var regionalApi = _hostUsingConfigureWithAClient.Services.GetRequiredService<IRegionalApi>();
            Assert.True(regionalApi.HttpClient.BaseAddress != null);

            var templateApi = _hostUsingConfigureWithAClient.Services.GetRequiredService<ITemplateApi>();
            Assert.True(templateApi.HttpClient.BaseAddress != null);

            var webhooksApi = _hostUsingConfigureWithAClient.Services.GetRequiredService<IWebhooksApi>();
            Assert.True(webhooksApi.HttpClient.BaseAddress != null);
        }

        /// <summary>
        /// Test dependency injection when using the configure method
        /// </summary>
        [Fact]
        public void ConfigureApiWithoutAClientTest()
        {
            var apiApplicationApi = _hostUsingConfigureWithoutAClient.Services.GetRequiredService<IApiApplicationApi>();
            Assert.True(apiApplicationApi.HttpClient.BaseAddress != null);

            var bulkSendApi = _hostUsingConfigureWithoutAClient.Services.GetRequiredService<IBulkSendApi>();
            Assert.True(bulkSendApi.HttpClient.BaseAddress != null);

            var documentApi = _hostUsingConfigureWithoutAClient.Services.GetRequiredService<IDocumentApi>();
            Assert.True(documentApi.HttpClient.BaseAddress != null);

            var meApi = _hostUsingConfigureWithoutAClient.Services.GetRequiredService<IMeApi>();
            Assert.True(meApi.HttpClient.BaseAddress != null);

            var regionalApi = _hostUsingConfigureWithoutAClient.Services.GetRequiredService<IRegionalApi>();
            Assert.True(regionalApi.HttpClient.BaseAddress != null);

            var templateApi = _hostUsingConfigureWithoutAClient.Services.GetRequiredService<ITemplateApi>();
            Assert.True(templateApi.HttpClient.BaseAddress != null);

            var webhooksApi = _hostUsingConfigureWithoutAClient.Services.GetRequiredService<IWebhooksApi>();
            Assert.True(webhooksApi.HttpClient.BaseAddress != null);
        }

        /// <summary>
        /// Test dependency injection when using the add method
        /// </summary>
        [Fact]
        public void AddApiWithAClientTest()
        {
            var apiApplicationApi = _hostUsingAddWithAClient.Services.GetRequiredService<IApiApplicationApi>();
            Assert.True(apiApplicationApi.HttpClient.BaseAddress != null);

            var bulkSendApi = _hostUsingAddWithAClient.Services.GetRequiredService<IBulkSendApi>();
            Assert.True(bulkSendApi.HttpClient.BaseAddress != null);

            var documentApi = _hostUsingAddWithAClient.Services.GetRequiredService<IDocumentApi>();
            Assert.True(documentApi.HttpClient.BaseAddress != null);

            var meApi = _hostUsingAddWithAClient.Services.GetRequiredService<IMeApi>();
            Assert.True(meApi.HttpClient.BaseAddress != null);

            var regionalApi = _hostUsingAddWithAClient.Services.GetRequiredService<IRegionalApi>();
            Assert.True(regionalApi.HttpClient.BaseAddress != null);

            var templateApi = _hostUsingAddWithAClient.Services.GetRequiredService<ITemplateApi>();
            Assert.True(templateApi.HttpClient.BaseAddress != null);

            var webhooksApi = _hostUsingAddWithAClient.Services.GetRequiredService<IWebhooksApi>();
            Assert.True(webhooksApi.HttpClient.BaseAddress != null);
        }

        /// <summary>
        /// Test dependency injection when using the add method
        /// </summary>
        [Fact]
        public void AddApiWithoutAClientTest()
        {
            var apiApplicationApi = _hostUsingAddWithoutAClient.Services.GetRequiredService<IApiApplicationApi>();
            Assert.True(apiApplicationApi.HttpClient.BaseAddress != null);

            var bulkSendApi = _hostUsingAddWithoutAClient.Services.GetRequiredService<IBulkSendApi>();
            Assert.True(bulkSendApi.HttpClient.BaseAddress != null);

            var documentApi = _hostUsingAddWithoutAClient.Services.GetRequiredService<IDocumentApi>();
            Assert.True(documentApi.HttpClient.BaseAddress != null);

            var meApi = _hostUsingAddWithoutAClient.Services.GetRequiredService<IMeApi>();
            Assert.True(meApi.HttpClient.BaseAddress != null);

            var regionalApi = _hostUsingAddWithoutAClient.Services.GetRequiredService<IRegionalApi>();
            Assert.True(regionalApi.HttpClient.BaseAddress != null);

            var templateApi = _hostUsingAddWithoutAClient.Services.GetRequiredService<ITemplateApi>();
            Assert.True(templateApi.HttpClient.BaseAddress != null);

            var webhooksApi = _hostUsingAddWithoutAClient.Services.GetRequiredService<IWebhooksApi>();
            Assert.True(webhooksApi.HttpClient.BaseAddress != null);
        }
    }
}
