/*
 * SignWell Developer API
 *
 * API for creating, managing, and tracking electronic signature workflows.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@signwell.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Xunit;
using Microsoft.Extensions.DependencyInjection;
using SignWell.Sdk.Raw;
using SignWell.Sdk.Models;


/* *********************************************************************************
*              Follow these manual steps to construct tests.
*              This file will not be overwritten.
*  *********************************************************************************
* 1. Navigate to ApiTests.Base.cs and ensure any tokens are being created correctly.
*    Take care not to commit credentials to any repository.
*
* 2. Mocking is coordinated by ApiTestsBase#AddApiHttpClients.
*    To mock the client, use the generic AddApiHttpClients.
*    To mock the server, change the client's BaseAddress.
*
* 3. Locate the test you want below
*      - remove the skip property from the Fact attribute
*      - set the value of any variables if necessary
*
* 4. Run the tests and ensure they work.
*
*/


namespace SignWell.Sdk.Test.Raw
{
    /// <summary>
    ///  Class for testing WebhooksApi
    /// </summary>
    public sealed class WebhooksApiTests : ApiTestsBase
    {
        private readonly IWebhooksApi _instance;

        public WebhooksApiTests() : base(Array.Empty<string>())
        {
            _instance = _host.Services.GetRequiredService<IWebhooksApi>();
        }

        /// <summary>
        /// Test CreateWebhook
        /// </summary>
        [Fact(Skip = "not implemented")]
        public async Task CreateWebhookAsyncTest()
        {
            CreateWebhookRequest createWebhookRequest = default!;
            var response = await _instance.CreateWebhookAsync(createWebhookRequest);
            var model = response.Created();
            Assert.IsType<WebhookResponse>(model);
        }

        /// <summary>
        /// Test DeleteWebhook
        /// </summary>
        [Fact(Skip = "not implemented")]
        public async Task DeleteWebhookAsyncTest()
        {
            Guid id = default!;
            await _instance.DeleteWebhookAsync(id);
        }

        /// <summary>
        /// Test ListWebhooks
        /// </summary>
        [Fact(Skip = "not implemented")]
        public async Task ListWebhooksAsyncTest()
        {
            var response = await _instance.ListWebhooksAsync();
            var model = response.Ok();
            Assert.IsType<List<WebhookResponse>>(model);
        }
    }
}
