/*
 * SignWell Developer API
 *
 * API for creating, managing, and tracking electronic signature workflows.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@signwell.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SignWell.Sdk.Models;
using SignWell.Sdk.Client;
using System.Reflection;

namespace SignWell.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing BulkSendCsvRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BulkSendCsvRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BulkSendCsvRequest
        //private BulkSendCsvRequest instance;

        public BulkSendCsvRequestTests()
        {
            // TODO uncomment below to create an instance of BulkSendCsvRequest
            //instance = new BulkSendCsvRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BulkSendCsvRequest
        /// </summary>
        [Fact]
        public void BulkSendCsvRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" BulkSendCsvRequest
            //Assert.IsType<BulkSendCsvRequest>(instance);
        }

        /// <summary>
        /// Test the property 'TemplateIds'
        /// </summary>
        [Fact]
        public void TemplateIdsTest()
        {
            // TODO unit test for the property 'TemplateIds'
        }

        /// <summary>
        /// Test the property 'BulkSendCsv'
        /// </summary>
        [Fact]
        public void BulkSendCsvTest()
        {
            // TODO unit test for the property 'BulkSendCsv'
        }
    }
}
