/*
 * SignWell Developer API
 *
 * API for creating, managing, and tracking electronic signature workflows.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@signwell.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SignWell.Sdk.Models;
using SignWell.Sdk.Client;
using System.Reflection;

namespace SignWell.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing CheckboxValidation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CheckboxValidationTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CheckboxValidation
        //private CheckboxValidation instance;

        public CheckboxValidationTests()
        {
            // TODO uncomment below to create an instance of CheckboxValidation
            //instance = new CheckboxValidation();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CheckboxValidation
        /// </summary>
        [Fact]
        public void CheckboxValidationInstanceTest()
        {
            // TODO uncomment below to test "IsType" CheckboxValidation
            //Assert.IsType<CheckboxValidation>(instance);
        }
    }
}
