/*
 * SignWell Developer API
 *
 * API for creating, managing, and tracking electronic signature workflows.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@signwell.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SignWell.Sdk.Models;
using SignWell.Sdk.Client;
using System.Reflection;

namespace SignWell.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing DocumentListResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DocumentListResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DocumentListResponse
        //private DocumentListResponse instance;

        public DocumentListResponseTests()
        {
            // TODO uncomment below to create an instance of DocumentListResponse
            //instance = new DocumentListResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DocumentListResponse
        /// </summary>
        [Fact]
        public void DocumentListResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" DocumentListResponse
            //Assert.IsType<DocumentListResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Documents'
        /// </summary>
        [Fact]
        public void DocumentsTest()
        {
            // TODO unit test for the property 'Documents'
        }

        /// <summary>
        /// Test the property 'CurrentPage'
        /// </summary>
        [Fact]
        public void CurrentPageTest()
        {
            // TODO unit test for the property 'CurrentPage'
        }

        /// <summary>
        /// Test the property 'TotalCount'
        /// </summary>
        [Fact]
        public void TotalCountTest()
        {
            // TODO unit test for the property 'TotalCount'
        }

        /// <summary>
        /// Test the property 'TotalPages'
        /// </summary>
        [Fact]
        public void TotalPagesTest()
        {
            // TODO unit test for the property 'TotalPages'
        }

        /// <summary>
        /// Test the property 'NextPage'
        /// </summary>
        [Fact]
        public void NextPageTest()
        {
            // TODO unit test for the property 'NextPage'
        }

        /// <summary>
        /// Test the property 'PreviousPage'
        /// </summary>
        [Fact]
        public void PreviousPageTest()
        {
            // TODO unit test for the property 'PreviousPage'
        }
    }
}
