/*
 * SignWell Developer API
 *
 * API for creating, managing, and tracking electronic signature workflows.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@signwell.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SignWell.Sdk.Models;
using SignWell.Sdk.Client;
using System.Reflection;

namespace SignWell.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing DocumentResponseFieldsInnerInnerRecipient
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DocumentResponseFieldsInnerInnerRecipientTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DocumentResponseFieldsInnerInnerRecipient
        //private DocumentResponseFieldsInnerInnerRecipient instance;

        public DocumentResponseFieldsInnerInnerRecipientTests()
        {
            // TODO uncomment below to create an instance of DocumentResponseFieldsInnerInnerRecipient
            //instance = new DocumentResponseFieldsInnerInnerRecipient();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DocumentResponseFieldsInnerInnerRecipient
        /// </summary>
        [Fact]
        public void DocumentResponseFieldsInnerInnerRecipientInstanceTest()
        {
            // TODO uncomment below to test "IsType" DocumentResponseFieldsInnerInnerRecipient
            //Assert.IsType<DocumentResponseFieldsInnerInnerRecipient>(instance);
        }

        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
    }
}
