/*
 * SignWell Developer API
 *
 * API for creating, managing, and tracking electronic signature workflows.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@signwell.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SignWell.Sdk.Models;
using SignWell.Sdk.Client;
using System.Reflection;

namespace SignWell.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing DocumentTemplateUpdateRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DocumentTemplateUpdateRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DocumentTemplateUpdateRequest
        //private DocumentTemplateUpdateRequest instance;

        public DocumentTemplateUpdateRequestTests()
        {
            // TODO uncomment below to create an instance of DocumentTemplateUpdateRequest
            //instance = new DocumentTemplateUpdateRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DocumentTemplateUpdateRequest
        /// </summary>
        [Fact]
        public void DocumentTemplateUpdateRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" DocumentTemplateUpdateRequest
            //Assert.IsType<DocumentTemplateUpdateRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Subject'
        /// </summary>
        [Fact]
        public void SubjectTest()
        {
            // TODO unit test for the property 'Subject'
        }

        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }

        /// <summary>
        /// Test the property 'Draft'
        /// </summary>
        [Fact]
        public void DraftTest()
        {
            // TODO unit test for the property 'Draft'
        }

        /// <summary>
        /// Test the property 'ExpiresIn'
        /// </summary>
        [Fact]
        public void ExpiresInTest()
        {
            // TODO unit test for the property 'ExpiresIn'
        }

        /// <summary>
        /// Test the property 'Reminders'
        /// </summary>
        [Fact]
        public void RemindersTest()
        {
            // TODO unit test for the property 'Reminders'
        }

        /// <summary>
        /// Test the property 'ApplySigningOrder'
        /// </summary>
        [Fact]
        public void ApplySigningOrderTest()
        {
            // TODO unit test for the property 'ApplySigningOrder'
        }

        /// <summary>
        /// Test the property 'ApiApplicationId'
        /// </summary>
        [Fact]
        public void ApiApplicationIdTest()
        {
            // TODO unit test for the property 'ApiApplicationId'
        }

        /// <summary>
        /// Test the property 'RedirectUrl'
        /// </summary>
        [Fact]
        public void RedirectUrlTest()
        {
            // TODO unit test for the property 'RedirectUrl'
        }

        /// <summary>
        /// Test the property 'AllowDecline'
        /// </summary>
        [Fact]
        public void AllowDeclineTest()
        {
            // TODO unit test for the property 'AllowDecline'
        }

        /// <summary>
        /// Test the property 'AllowReassign'
        /// </summary>
        [Fact]
        public void AllowReassignTest()
        {
            // TODO unit test for the property 'AllowReassign'
        }

        /// <summary>
        /// Test the property 'DeclineRedirectUrl'
        /// </summary>
        [Fact]
        public void DeclineRedirectUrlTest()
        {
            // TODO unit test for the property 'DeclineRedirectUrl'
        }

        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Fact]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }

        /// <summary>
        /// Test the property 'Labels'
        /// </summary>
        [Fact]
        public void LabelsTest()
        {
            // TODO unit test for the property 'Labels'
        }

        /// <summary>
        /// Test the property 'CheckboxGroups'
        /// </summary>
        [Fact]
        public void CheckboxGroupsTest()
        {
            // TODO unit test for the property 'CheckboxGroups'
        }
    }
}
