/*
 * SignWell Developer API
 *
 * API for creating, managing, and tracking electronic signature workflows.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@signwell.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SignWell.Sdk.Models;
using SignWell.Sdk.Client;
using System.Reflection;

namespace SignWell.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing ErrorResponseMeta
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ErrorResponseMetaTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ErrorResponseMeta
        //private ErrorResponseMeta instance;

        public ErrorResponseMetaTests()
        {
            // TODO uncomment below to create an instance of ErrorResponseMeta
            //instance = new ErrorResponseMeta();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ErrorResponseMeta
        /// </summary>
        [Fact]
        public void ErrorResponseMetaInstanceTest()
        {
            // TODO uncomment below to test "IsType" ErrorResponseMeta
            //Assert.IsType<ErrorResponseMeta>(instance);
        }

        /// <summary>
        /// Test the property 'Error'
        /// </summary>
        [Fact]
        public void ErrorTest()
        {
            // TODO unit test for the property 'Error'
        }

        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }

        /// <summary>
        /// Test the property 'Messages'
        /// </summary>
        [Fact]
        public void MessagesTest()
        {
            // TODO unit test for the property 'Messages'
        }
    }
}
