/*
 * SignWell Developer API
 *
 * API for creating, managing, and tracking electronic signature workflows.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@signwell.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SignWell.Sdk.Models;
using SignWell.Sdk.Client;
using System.Reflection;

namespace SignWell.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing FieldsInnerInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FieldsInnerInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FieldsInnerInner
        //private FieldsInnerInner instance;

        public FieldsInnerInnerTests()
        {
            // TODO uncomment below to create an instance of FieldsInnerInner
            //instance = new FieldsInnerInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FieldsInnerInner
        /// </summary>
        [Fact]
        public void FieldsInnerInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" FieldsInnerInner
            //Assert.IsType<FieldsInnerInner>(instance);
        }

        /// <summary>
        /// Test the property 'X'
        /// </summary>
        [Fact]
        public void XTest()
        {
            // TODO unit test for the property 'X'
        }

        /// <summary>
        /// Test the property 'Y'
        /// </summary>
        [Fact]
        public void YTest()
        {
            // TODO unit test for the property 'Y'
        }

        /// <summary>
        /// Test the property 'Page'
        /// </summary>
        [Fact]
        public void PageTest()
        {
            // TODO unit test for the property 'Page'
        }

        /// <summary>
        /// Test the property 'RecipientId'
        /// </summary>
        [Fact]
        public void RecipientIdTest()
        {
            // TODO unit test for the property 'RecipientId'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'Required'
        /// </summary>
        [Fact]
        public void RequiredTest()
        {
            // TODO unit test for the property 'Required'
        }

        /// <summary>
        /// Test the property 'Label'
        /// </summary>
        [Fact]
        public void LabelTest()
        {
            // TODO unit test for the property 'Label'
        }

        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Fact]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }

        /// <summary>
        /// Test the property 'ApiId'
        /// </summary>
        [Fact]
        public void ApiIdTest()
        {
            // TODO unit test for the property 'ApiId'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Validation'
        /// </summary>
        [Fact]
        public void ValidationTest()
        {
            // TODO unit test for the property 'Validation'
        }

        /// <summary>
        /// Test the property 'FixedWidth'
        /// </summary>
        [Fact]
        public void FixedWidthTest()
        {
            // TODO unit test for the property 'FixedWidth'
        }

        /// <summary>
        /// Test the property 'LockSignDate'
        /// </summary>
        [Fact]
        public void LockSignDateTest()
        {
            // TODO unit test for the property 'LockSignDate'
        }

        /// <summary>
        /// Test the property 'DateFormat'
        /// </summary>
        [Fact]
        public void DateFormatTest()
        {
            // TODO unit test for the property 'DateFormat'
        }

        /// <summary>
        /// Test the property 'Height'
        /// </summary>
        [Fact]
        public void HeightTest()
        {
            // TODO unit test for the property 'Height'
        }

        /// <summary>
        /// Test the property 'Width'
        /// </summary>
        [Fact]
        public void WidthTest()
        {
            // TODO unit test for the property 'Width'
        }

        /// <summary>
        /// Test the property 'Options'
        /// </summary>
        [Fact]
        public void OptionsTest()
        {
            // TODO unit test for the property 'Options'
        }

        /// <summary>
        /// Test the property 'DefaultOption'
        /// </summary>
        [Fact]
        public void DefaultOptionTest()
        {
            // TODO unit test for the property 'DefaultOption'
        }

        /// <summary>
        /// Test the property 'AllowOther'
        /// </summary>
        [Fact]
        public void AllowOtherTest()
        {
            // TODO unit test for the property 'AllowOther'
        }
    }
}
