/*
 * SignWell Developer API
 *
 * API for creating, managing, and tracking electronic signature workflows.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@signwell.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SignWell.Sdk.Models;
using SignWell.Sdk.Client;
using System.Reflection;

namespace SignWell.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing FileFormat
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FileFormatTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FileFormat
        //private FileFormat instance;

        public FileFormatTests()
        {
            // TODO uncomment below to create an instance of FileFormat
            //instance = new FileFormat();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FileFormat
        /// </summary>
        [Fact]
        public void FileFormatInstanceTest()
        {
            // TODO uncomment below to test "IsType" FileFormat
            //Assert.IsType<FileFormat>(instance);
        }
    }
}
