/*
 * SignWell Developer API
 *
 * API for creating, managing, and tracking electronic signature workflows.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@signwell.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SignWell.Sdk.Models;
using SignWell.Sdk.Client;
using System.Reflection;

namespace SignWell.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing PlaceholdersInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PlaceholdersInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PlaceholdersInner
        //private PlaceholdersInner instance;

        public PlaceholdersInnerTests()
        {
            // TODO uncomment below to create an instance of PlaceholdersInner
            //instance = new PlaceholdersInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PlaceholdersInner
        /// </summary>
        [Fact]
        public void PlaceholdersInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" PlaceholdersInner
            //Assert.IsType<PlaceholdersInner>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'PreassignedRecipientName'
        /// </summary>
        [Fact]
        public void PreassignedRecipientNameTest()
        {
            // TODO unit test for the property 'PreassignedRecipientName'
        }

        /// <summary>
        /// Test the property 'PreassignedRecipientEmail'
        /// </summary>
        [Fact]
        public void PreassignedRecipientEmailTest()
        {
            // TODO unit test for the property 'PreassignedRecipientEmail'
        }
    }
}
