/*
 * SignWell Developer API
 *
 * API for creating, managing, and tracking electronic signature workflows.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@signwell.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SignWell.Sdk.Models;
using SignWell.Sdk.Client;
using System.Reflection;

namespace SignWell.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing TemplateRecipientsInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TemplateRecipientsInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TemplateRecipientsInner
        //private TemplateRecipientsInner instance;

        public TemplateRecipientsInnerTests()
        {
            // TODO uncomment below to create an instance of TemplateRecipientsInner
            //instance = new TemplateRecipientsInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TemplateRecipientsInner
        /// </summary>
        [Fact]
        public void TemplateRecipientsInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" TemplateRecipientsInner
            //Assert.IsType<TemplateRecipientsInner>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'PlaceholderName'
        /// </summary>
        [Fact]
        public void PlaceholderNameTest()
        {
            // TODO unit test for the property 'PlaceholderName'
        }

        /// <summary>
        /// Test the property 'Passcode'
        /// </summary>
        [Fact]
        public void PasscodeTest()
        {
            // TODO unit test for the property 'Passcode'
        }

        /// <summary>
        /// Test the property 'Subject'
        /// </summary>
        [Fact]
        public void SubjectTest()
        {
            // TODO unit test for the property 'Subject'
        }

        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }

        /// <summary>
        /// Test the property 'SendEmail'
        /// </summary>
        [Fact]
        public void SendEmailTest()
        {
            // TODO unit test for the property 'SendEmail'
        }

        /// <summary>
        /// Test the property 'SendEmailDelay'
        /// </summary>
        [Fact]
        public void SendEmailDelayTest()
        {
            // TODO unit test for the property 'SendEmailDelay'
        }
    }
}
